### ISSUE TITLE
Firefox: decimal() input's step="any" not working as intended

### ISSUE THREAD

**Issue by kuopassa** [litecart/litecart#103]
Inside **func_form.inc.php** there's that **form_draw_decimal_field()** which creates an input field that has **step="any"**, but it's not working in Mozilla Firefox. In Firefox that **step="any"** behaves so that when at the right side of input field the small arrow up/down is clicked, number is increased/decreased to next whole number. So that means user can't create for example 5.5 using the small arrow buttons.

This issue is in LiteCart 2.1. and 2.0.2, maybe other versions as well.

**Comment by litecart** [comment]
What is the expected behavior when clicking an arrow up or down?

**Comment by kuopassa** [comment]
To be able to press an arrow so the number is increased/decreased with some decimal accuracy. So for example if such an input field has **step="0.5"**, then the button will increase/decrease with steps of 0.5. If it's **step="0.02"** then value will increase/decrease with 0.02 precision, like so:

Initial value: 0
Clicking upward arrow, value becomes: 0.02
Clicking upward arrow, value becomes. 0.04
Clicking upward arrow, value becomes. 0.06
Clicking downward arrow, value becomes: 0.04

**Comment by litecart** [comment]
With a precision of 0.02 it would require 50 clicks to raise value $1. With a precision of 0.5 I don't think it serves no good potential for decimal accuracy. People most likely would need to type the numbers anyway for e.g. 1.99. Which brings me to the conclusion of the Firefox behavior. It might not be a bug but of design.

Unless it's 0.01 it will most likely require typing. And stepping cents up will take forever to set a price like 199 using 0.01.

**Comment by kuopassa** [comment]
Sure, it's of course your call. :-]

**Comment by litecart** [comment]
Closing this for now. If something else pops up in the future we will deal with it then.
