### ISSUE TITLE
Missing product price calculation in Safari (MacOsX)

### ISSUE THREAD

**Issue by areasas** [litecart/litecart#113]
What were you trying to do?
- Managing options in product order

What was expected to happen?
- Product price change when different options are selected (it is not ok in Safari while ok in Firefox)

What was the actual result - what exactly did happen?
- Product price does not change (in Safari)

Which LiteCart version are you running?
- 2.1.1 (PHP 7.1)

![schermata 2018-03-07 alle 12 57 31](https://user-images.githubusercontent.com/2221328/37091296-e885f7d6-2207-11e8-9185-d75c363632d9.png)
![schermata 2018-03-07 alle 12 58 05](https://user-images.githubusercontent.com/2221328/37091298-e8a8ac54-2207-11e8-9c0c-70add3b8421a.png)

**Comment by litecart** [comment]
Thank you for reporting. Is there a javascript error shown in the browser console?

**Comment by areasas** [comment]
Safari does not indicate any error!
![schermata 2018-03-07 alle 22 13 46](https://user-images.githubusercontent.com/2221328/37118544-e4f62fbc-2254-11e8-82a7-447427a7bd3f.png)

**Comment by rob-lindman** [comment]
I have a mac now, what is the 'help wanted'?

**Comment by timint** [comment]
I'm not sure. I think I'm gonna close this thread as it seems to be related to an add-on rather than options.
