### ISSUE TITLE
Meta title not translated

### ISSUE THREAD

**Issue by domugo** [litecart/litecart#114]
Meta title (browser and page source) is being shown in default language.

**Comment by litecart** [comment]
For all pages? Are you sure this is translated in Admin -> Translations?

**Comment by domugo** [comment]
Sorry, not all pages. Only homepage. The one translation which by default says "Online store". And yes, I've translated this in admin, but it uses default language for all other languages.

**Comment by litecart** [comment]
Cannot be reproduced. Show a screenshot of your translation please.

**Comment by domugo** [comment]
Updated to github release and it solved my issue. Sorry.
