### ISSUE TITLE
email password (too) visible in the backend

### ISSUE THREAD

**Issue by rob-lindman** [litecart/litecart#115]
What were you trying to do?
change email settings

What was expected to happen?
password should be invisible or marked by ********

What was the actual result - what exactly did happen?
i can see the password for my email account in the clear, and if I have a partner access the site for catalog maintenance, I don't necessarily want them to have it.

Which LiteCart version are you running?
the most awesome one with all the files patched and up to date

**Comment by litecart** [comment]
The most awesome one :) Haha

To turn this into a password field edit the setting in lc_settings and set function to "password()" rather than "input()".

A reference to a fix will be attached to this thread once comitted.

Thank you
