### ISSUE TITLE
Please insert some more Functions | Wanna use JS

### ISSUE THREAD

**Issue by Fefke** [litecart/litecart#116]
What were you trying to do?
I am trying to build an new Add-on and bring in some Inputs for Settings.

What would you change?
Please insert an function in the settings() function to write own code in there.
-> There is no Keyword for empty or write your own in func_form.inc.php

Make an easy to integreate API

Which LiteCart version are you running?
Newwest: 2.1.1

**Comment by timint** [comment]
Inserting PHP code in a field input is definately a no go. The whole purpose with vqmod is to provide almost unlimited possibilites of executing custom code.
