### ISSUE TITLE
no reactions of "uninstall()" function

### ISSUE THREAD

**Issue by Fefke** [litecart/litecart#118]
What were you trying to do?
I am trying to uninstall my module/ add-on

What was expected to happen?
An working script (tested it) should delete some Data from Database

What was the actual result - what exactly did happen?
Nothing happend... the Data is still there!

Which LiteCart version are you running?
Newest: 2.1.1

P.S.: Ask for my code if needed

**Comment by timint** [comment]
The method is called from ctrl_module.inc.php line 140.

      if (method_exists($this->_module, 'uninstall')) {
        $this->_module->uninstall();
      }

Try to do some debugging there.

Keep in mind it is also ran upon install before install() to remove traces of previous installations if removed without uninstalling it.

**Comment by Fefke** [comment]
The last option confused me at first.
My meaning is… I can’t connect to the Database to delete configurations.
Normaly should the given database class work within every other method,
isn’t it?

Von: T. Almroth
Gesendet: Dienstag, 24. April 2018 03:55
An: litecart/litecart
Cc: Fefke; Author
Betreff: Re: [litecart/litecart] no reactions of "uninstall()" function (#118)

The method is called from ctrl_module.inc.php line 140.
  if (method_exists($this->_module, 'uninstall')) {
    $this->_module->uninstall();
  }
Try to do some debugging there.
Keep in mind it is also ran upon install before install() to remove traces of previous installations if removed without uninstalling it.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by timint** [comment]
The database class works globally. database::query()

Is this still an issue?
