### ISSUE TITLE
Issues with checkout (v2 alpha dev)

### ISSUE THREAD

**Issue by domugo** [litecart/litecart#12]
I've tried using checkout page and it has multiple issues.
First it has some issues with customers details input. After saving information it doesn't allow to confirm order. A popup shows up next to the browser "back" button saying "please fill in the field. Not sure what field, because it doesn't show anything else. 

I can confirm order after refreshing the page with saved data for customer. After confirming the order order copy email shows some error in both shipping and billing addresses: 
Notice: Undefined variable: zone in ~/includes/references/ref_country.inc.php on line 98
Notice: Undefined index: in ~/includes/references/ref_country.inc.php on line 98

Total amount is also incorrect. For me it shows 2x amount minus shipping fee. 

Using latest version Firefox. Not sure if this happens in any other browsers.

**Comment by timint** [comment]
Are the errors obvious or do we need a certain currency or country configuration to simulate this?

**Comment by domugo** [comment]
"Please fill out this field" notice keeps showing everything when entering customer data.
Email notice is wrong also every time, but total amount is sometimes correct. Can be sure how to simulate this one. 

Here's a pic for notice if this helps.
![untitled](https://cloud.githubusercontent.com/assets/16509653/22842362/9a1b2c90-efdd-11e6-9952-e690f0b5d989.jpg)
