### ISSUE TITLE
Notice: Undefined index: name in ~/includes/library/lib_cart.inc.php on line 165

### ISSUE THREAD

**Issue by juancrescente** [litecart/litecart#122]
I've added a new language and when I'm going to upload the translation I got this in the admin

Notice: Undefined index: name in ~/includes/library/lib_cart.inc.php on line 165

The URL with the error is:
http://localhost/litecart-2.1.2/public_html/admin/?app=translations&doc=search

LiteCart 2.1.2

**Comment by juancrescente** [comment]
Actually it is in all pages in admin

**Comment by juancrescente** [comment]
I'm also getting this 

Notice: Undefined variable: setting in ~/admin/appearance.app/template_settings.inc.php on line 89
Notice: Undefined variable: setting in ~/admin/appearance.app/template_settings.inc.php on line 89
Notice: Undefined variable: setting in ~/admin/appearance.app/template_settings.inc.php on line 89
Notice: Undefined variable: setting in ~/admin/appearance.app/template_settings.inc.php on line 89


in template settings

**Comment by juancrescente** [comment]
Now in the store when I add a product I get

Error while updating cart

**Comment by juancrescente** [comment]
Now I cannot disable spanish:

" No es posible desactivar el idioma predeterminado"

seems like very buggy

**Comment by juancrescente** [comment]
I tried to re-install and I'm getting this now:

Notice:
date_default_timezone_set(): Timezone ID 'America/Argentina' is invalid in
~/includes/library/lib_settings.inc.php
on line
25


What's going on!!

**Comment by timint** [comment]
I'm closing this issue as it's pointlesd trying to answer a thread like this. Try not to spin off topic.
