### ISSUE TITLE
Time zones for Argentina broken

### ISSUE THREAD

**Issue by juancrescente** [litecart/litecart#123]
I get a lot of 
America/Argentina
America/Argentina
America/Argentina

when selecting the time zone in the setup, and then in the admin

Notice: date_default_timezone_set(): Timezone ID 'America/Argentina' is invalid in ~/includes/library/lib_settings.inc.php on line 25

LiteCart 2.1.2

**Comment by timint** [comment]
Thank you for reporting. I will make sure this gets patched.
