### ISSUE TITLE
Error when uploading csv with translation

### ISSUE THREAD

**Issue by juancrescente** [litecart/litecart#124]
Fresh install, upload spanish translation

Fatal error: 1054 - Unknown column 'text_es' in 'field list' update `litecart`.`lc_translations` set text_es = 'Categorías' where code = 'categories:head_title' limit 1; in ~/includes/library/lib_database.inc.php on line 225

**Comment by timint** [comment]
Did you create the Spanish language first?

**Comment by juancrescente** [comment]
Yes, it was because Quantity units was not defined for spanish. Maybe it should fallback to something?

**Comment by timint** [comment]
The quantity unit is the answer to your other thread regarding the notice in lib_cart.inc.php.

This fatal error indicates the spanish column is not yet created in the translations table. It is created when you create the language.
