### ISSUE TITLE
Default store language 

### ISSUE THREAD

**Issue by juancrescente** [litecart/litecart#125]
I've set Spanish as a default language and for the store language. 
When I access the site, I expect to get es/ as a default language.
http://localhost/litecart/public_html

Instead it redirects to en/
The only solution so far is to disable english language

LiteCart 2.1.2

**Comment by timint** [comment]
What is your browser locale? The defaul language is a last destination fallback if all identify rules fail.

**Comment by juancrescente** [comment]
I see, it is

navigator.browserLanguage: undefined
navigator.language: en-US

so it deafults to the browsers locale, I thought it was to the defined store locale

**Comment by timint** [comment]
You can change this behavior in lib_language.inc.php in the method identify().
