### ISSUE TITLE
die() is called when deleting a vQmod

### ISSUE THREAD

**Issue by juancrescente** [litecart/litecart#126]
In file
**https://github.com/litecart/litecart/blob/dev/public_html/admin/vqmods.app/vqmods.inc.php**
in line 33, there's a die call that should be removed when a vQmod is deleted from admin 

`die(FS_DIR_HTTP_ROOT . WS_DIR_HTTP_HOME .'vqmod/xml/'. pathinfo($vqmod, PATHINFO_BASENAME));
`
This cause the admin to exit and print the vQmod name instead of deleting it

**Comment by timint** [comment]
Should not happen, and yet it did.
Thank you for reporting. A commit will be referenced.
