### ISSUE TITLE
Failure in Quantity | Loops or Multiplys, Add's?

### ISSUE THREAD

**Issue by Fefke** [litecart/litecart#127]
What were you trying to do?
I tried to pay for the right Quantity of products. (test store)

What was expected to happen?
I wanted to buy 3 Red Duck's, at the end there was 431 (picture following)

What was the actual result - what exactly did happen?
After some refreshes of the page the Quantity was multiplied by 112... after every refresh it's getting more and more...

![1](https://user-images.githubusercontent.com/33942165/40585024-d3e4e448-61ab-11e8-8403-ffd9d048ad5d.PNG)

![2](https://user-images.githubusercontent.com/33942165/40585043-0dceb6fc-61ac-11e8-9817-4dea7fbc2a5a.PNG)

Which LiteCart version are you running?
Newest: Version 2.1.2

**Comment by timint** [comment]
Can this be reproduced in the demo? Please provide instructions how it can be reproduced.

**Comment by Fefke** [comment]
I try to reproduce it... but I font know how much time is needed...
sometimes it comes and then its away for an very long time...

T. Almroth <notifications@github.com> schrieb am Mo., 28. Mai 2018, 17:06:

**Comment by timint** [comment]
I can confirm this issue. I have been able to reproduce it and I am looking for a solution.

It seems to occur when a guest shopping cart is merged with a customer cart where the same item is already present in the cart.
