### ISSUE TITLE
Notice: Undefined variable: locale_charset in ~/includes/library/lib_language.inc.php

### ISSUE THREAD

**Issue by sabeti05** [litecart/litecart#129]
What were you trying to do?
I'm trying to add a new language in admin panel / Languages, I can see the same error for default language too.

What was the actual result - what exactly did happen?
There's notices:
Notice: Undefined variable: locale_charset in ~/includes/library/lib_language.inc.php on line 275

Which LiteCart version are you running?
LiteCart 2.1.2

Thanks

**Comment by timint** [comment]
What charset are you running?

Can you try the following:

In lib_language.inc.php

**Find**

          case (preg_match('#\.(874|1256)$#', $locale, $matches)):
            return iconv('UTF-8', "$locale_charset", strftime($format, $timestamp));

**Replace with**

          case (preg_match('#\.(874)$#', $locale, $matches)):
            return iconv('UTF-8', $locale, strftime($format, $timestamp));

**Comment by sabeti05** [comment]
Thank you for your reply.
I didn't enter any value there. I just wanted to inform you that there's such issue.

Thanks

**Comment by timint** [comment]
You need a charset for your language. I recommend setting UTF-8.
Admin -> Languages -> Edit Language -> Charset: UTF-8
