### ISSUE TITLE
Unuseable Zone-/s Selection (Problem localized)

### ISSUE THREAD

**Issue by Fefke** [litecart/litecart#133]
What were you trying to do?
Create a Zone Input for an Add-on

What was expected to happen?
A list of chooseable zones is selectable

What was the actual result - what exactly did happen?
an unuseable Select block

Which LiteCart version are you running?
2.1.3

=> func_form.inc.php | Line: 578
break missing?

**Comment by Fefke** [comment]
Following:
I inserted a break but it is still not working...

**Comment by timint** [comment]
You don't need a break since a return escapes the function and processess nothing more in it. What does your code look like? If no country is passed it will use the country for the store. try `zone("XX")`

**Comment by Fefke** [comment]
I am sorry, I never tried to make a switch statement without breaking any case. I learned it's way and I think it's important to work clean.
So let us just forget this, I have to ask my Teachers about things like this... I'm learning something new every day

But no one of both functions (zone || zones) are working... I try to find the failure, but I can tell an "select" Element is loaded.

**Comment by timint** [comment]
Where are you trying to create this setting? In a module?

```
      array(
        'key' => 'zone_code',
        'default_value' => '',
        'title' => '....',
        'description' => '....,
        'function' => 'zone("US")',
      ),
```
