### ISSUE TITLE
divs being replaced by <p> tags in the page editor

### ISSUE THREAD

**Issue by zenclrk** [litecart/litecart#138]
What were you trying to do?

**I created a page with a photo gallery on it.**

What was expected to happen?

**The html i put into the editor should be saved like i entered it.**

What was the actual result - what exactly did happen?

**After several minutes my divs were replaced by <p> tags**

Which LiteCart version are you running?

**LiteCart 2.1.3**

**Comment by zenclrk** [comment]
I was able to find this. 

https://github.com/Alex-D/Trumbowyg/issues/621

It looks like I can probably find the line of code they mention and remove it. Thanks for the help!

**Comment by timint** [comment]
Interesting. Let me know if that fixes this issue and I will add it to LiteCart. :)

**Comment by litecart** [comment]
A fix is committed here:
https://github.com/litecart/litecart/commit/3012fcdfcd5e3710059351324007a8b19ef0a20b
