### ISSUE TITLE
litecart forums spamming inbox

### ISSUE THREAD

**Issue by rob-lindman** [litecart/litecart#141]
What were you trying to do?
live

What was expected to happen?
not much

What was the actual result - what exactly did happen?
a bunch of chinese crap email is coming in 

Which LiteCart version are you running?
the one on litecart's website

hey TiM hope you are doing well, it seems that someone is spamming the litecart site with chinese garbage and that is going out to email inboxes of people who subscribe...

**Comment by timint** [comment]
Yes I noticed. I have battled spam with several different ideas now. Besides captcha there are bot traps, session security, ip reputation, origin check. But these evil spammers always find a way through. I have some new ideas I will try.

**Comment by rob-lindman** [comment]
some mechanism for throttling the number of posts within a 5 minute period might be adequate?

**Comment by domugo** [comment]
Is the forum still locked? I see some users can already post and I'm still blocked.

**Comment by rob-lindman** [comment]
I am still receiving spam. It looks like email goes out before you delete the topics from the website. I like litecart and I want to be informed of new topics and developments, but I do not want to receive emails written by chinese "hackers". Is there a way you could perhaps put a delay on email going out on new topics? maybe I should just unsubscribe or something but that feels like evil is winning.

**Comment by rob-lindman** [comment]
I haven't seen any chinese spam from the forums for a little bit so I am of the belief that TiM is winning and I will close the issue.

**Comment by timint** [comment]
Maybe they realized it wasn't worth the trouble keep trying. It's a lot of trouble they go through for just one attack of posting. And they only remain a short time until deleted.
