### ISSUE TITLE
how to fixed Payment module. I do get this error when i click on payment module in admin panel 

### ISSUE THREAD

**Issue by ikeogu** [litecart/litecart#143]
What were you trying to do? ---
 install a payment module from admin panel

What was expected to happen?----
 see an added module from payment folder
What was the actual result - what exactly did happen?-----
Fatal error: Uncaught Error: Class 'pm_mymodule' not found in C:\Bitnami\wampp\apache2\htdocs\litecart-2.1.4\public_html\admin\modules.app\modules.inc.php:110 Stack trace: #0 C:\Bitnami\wampp\apache2\htdocs\litecart-2.1.4\public_html\admin\index.php(125): include() #1 {main} thrown in C:\Bitnami\wampp\apache2\htdocs\litecart-2.1.4\public_html\admin\modules.app\modules.inc.php on line 110
 

Which LiteCart version are you running?
itecart-2.1.4

**Comment by timint** [comment]
The classname must correspond to the filename.

This is not a support channel. Please turn to the forums.

**Comment by ikeogu** [comment]
thanks for your response. they are actually the same thing, i wonder why i
am having such issues, i am kind of stucked here and don't know what to do.

**Comment by timint** [comment]
You can turn to the forums and show your code.
