### ISSUE TITLE
Not inserting updated 

### ISSUE THREAD

**Issue by arshidkv12** [litecart/litecart#144]
What were you trying to do?
Not reflecting updated data in the checkout page. 
Example: Quantity change not reflecting in orders table ( Please try failure payment first then not adding new order_uid or updated new data but new order_uid is getting in the front end)

Which LiteCart version are you running?
2.1.4

  I think    `    public function transfer( $order ) `  has some issue.

**Comment by timint** [comment]
Sorry I did not understand that.

**Comment by arshidkv12** [comment]
First do failure payment then change product quality in checkout page, then you can see it is not updating in orders table.

**Comment by postnummersok** [comment]
By failure payment, do you mean the option shows an error notice. Or do you mean you were thrown back to checkout from a failed payment. Have you checked the Browser console for javascript errors?

**Comment by timint** [comment]
By failure payment, do you mean the option shows an error notice. Or do you mean you were thrown back to checkout from a failed payment. Have you checked the Browser console for javascript errors?

**Comment by timint** [comment]
Closing as insufficient lead.
