### ISSUE TITLE
Editing country in admin

### ISSUE THREAD

**Issue by domugo** [litecart/litecart#145]
What were you trying to do?
EDIT country details in admin. Currency code for Lithuania should be EUR, not LTL.

What was expected to happen?
Trying to save changes

What was the actual result - what exactly did happen?
Can't save new changes due to field: Code (ISO 3166-1 numeric). It's asking to match requested format. 

Which LiteCart version are you running?
2.1.4., Reproduced in demo also.

**Comment by botonakis** [comment]
The problem is known. 

The field expects: [A-Z]{2}
So to be able to save it for now add LT into the text field and Save Changes.

Not known bugs (yet) if you change this from 440 to LT.

**Comment by timint** [comment]
This is a known bug, patched in dev branch Nov 2. It will be out next master release.
https://github.com/litecart/litecart/commit/a5d4c285fce2d321c12e44cdd12803fd598be578#diff-f51644cbb7472a1992fdf82714094575
