### ISSUE TITLE
Wrong categories shown in url for similar products and also purchased products

### ISSUE THREAD

**Issue by domugo** [litecart/litecart#146]
Product Green duck created with url like this:
https://demo.litecart.net/vegan-vibes-c-3/green-duck-p-2

Product Yellow duck created with url like this:
https://demo.litecart.net/rubber-ducks-c-1/yellow-duck-p-1

There is a bug in also purchased and similar products for creating product link. It uses current product category and not the one that the product in the box is mapped to.

Opened product Green duck and url for yelllow duck in similar box is wrong:
https://demo.litecart.net/vegan-vibes-c-3/yellow-duck-p-1 
Also bredcrumbs is wrong after opening the link. And vice versa.

Which LiteCart version are you running?
Latest, also reproduced in demo.

**Comment by timint** [comment]
Confirmed. This problem resides in draw_listing_product() which does not make an exception when it's a similar or also purchased product.
