### ISSUE TITLE
error when trying to add new currency

### ISSUE THREAD

**Issue by sakaljurgis** [litecart/litecart#149]
Hello,
- small bug in the public_html/admin/currencies.app/edit_currency.inc.php row 34. language class should be entered instead of currency:
`throw new Exception(currency::translate('error_currency_already_exists', 'The currency already exists in the database'));`
- and please check the loop in the public_html/includes/controllers/ctrl_product.inc.php row 282 it looks like this one is unnecessary as it is repeated in row 300 (same loop inside this loop)
`foreach (array_keys(currency::$currencies) as $currency_code) {`

**Comment by timint** [comment]
Well spotted. Thank you for reporting. :)
