### ISSUE TITLE
Cannot delete Product Group

### ISSUE THREAD

**Issue by SkipperHosting** [litecart/litecart#153]
Which LiteCart version are you running?
2.1.6 - possible to recreate in LC demo store

Cannot delete a Product Group once created.  Results in error: 'You must provide a product group'

This is tied to a variable typo in /admin/catalog.app/edit_product_group.inc.php :: 47
`      if (empty($option_group->data['id'])) throw new Exception(language::translate('error_must_provide_product_group', 'You must provide a product group'));
`
Variable should be $product_group
`      if (empty($product_group->data['id'])) throw new Exception(language::translate('error_must_provide_product_group', 'You must provide a product group'));
`

I am not sure this is an issue with dev branch, as this file is not even present.  Nor have I played with the latest instance.

**Comment by timint** [comment]
I think this was patched in a commit to the dev branch but product groups was later replaced by product attributes and attributes filter.

**Comment by timint** [comment]
Closed as not an issue in coming version
