### ISSUE TITLE
SMTP auth types not properly parsed from server reply

### ISSUE THREAD

**Issue by SkipperHosting** [litecart/litecart#154]
![image](https://user-images.githubusercontent.com/359192/33850066-ef37afea-deb2-11e7-932f-ba876fb9060b.png)

SMTP with GMail works fine for me. I will be pushing some commits later this evening that enables a log file being created for your last SMTP session. You might wanna check it out.

Your error message says only a character "C"is all that was identified from the following:

```
        if (preg_match('#250.AUTH ([^\R]+)#', $this->_last_response, $matches)) {
          $auths = explode(' ', $matches[1]);
        }
```

Makes me wonder if your smtp server returned:
`250.AUTH C`

_Originally posted by @timint in https://github.com/litecart/litecart/issues/98#issuecomment-350834990_

**Comment by SkipperHosting** [comment]
((Sorry for connecting to an old topic, but this seemed to describe quite similar behavior.))

During some local testing, an issue was noticed with the SMTP authentication triaging routine.
In v2.1.6, it is in file: /includes/classes/smtp.inc.php :: LINE 81
In latest dev branch, it is in file: /includes/wrappers/wrap_smtp.inc.php :: LINE 81

The problem is that the '250 Auth' response line from the server is not properly pattern matched and the resulting $auths array does not contain clean types (LOGIN, PLAIN, etc).  But, rather contains the words with potential trailing newline characters that then fail the following case tests (falling through to the 'PLAIN' method regardless of the other possible methods).

This stems from the following quote from the PCRE regex standard (http://www.pcre.org/pcre.txt):

> \N  is not allowed in a character class. \B, \R, and \X are not special inside a character class. Like  other  unrecognized  escape  sequences, they  are  treated  as  the  literal  characters  "B",  "R", and "X" by default, but cause an error if the PCRE_EXTRA option is set. Outside  a character class, these sequences have different meanings.

The regex pattern for this breakdown:
`preg_match('#250.AUTH ([^\R]+)#',...`
uses '\R' incorrectly, and thus the pattern fails to match as expected.

Unfortunately, it appears a more verbose version of the pattern must be used instead when inside a character class, something like:
`preg_match('#250.AUTH ([^\n\r]+)#',...`

Notes:
My server response line was:
'250 AUTH PLAIN LOGIN'
With the pattern, as written, this would result in the array ['PLAIN', 'LOGIN\r\n'].  With the order of the switch cases, 'LOGIN' would never have opportunity of triggering, and would fall-back to 'PLAIN' as the only possible match.

**Comment by SkipperHosting** [comment]
In character classes, \R is treated as a literal 'R'.  Which would exhibit the result described if the AUTH line returned were something like:
250 AUTH CRAM-MD5...
The resultant pattern match would only be the letter 'C' (because of the literal 'R' immediately thereafter)

**Comment by timint** [comment]
Great job troubleshooting this and providing good references. I learned something new from this.

Does the following return the result you expected?:

#250.AUTH (.*?)\r\n#

I think it's safe to use \r\n since it's the RFC standard for emails. I don't know if there are smtp servers that would return only \r or \n for line breaking.

**Comment by SkipperHosting** [comment]
Your pattern works for me, thanks.

**Comment by timint** [comment]
#250.AUTH (.*?)\R# should work as well. Maybe even better.
