### ISSUE TITLE
Password loses coherence with email

### ISSUE THREAD

**Issue by SkipperHosting** [litecart/litecart#159]
Customer password can become invalid when changing email address in either front- or back-office.

v2.2 from latest dev branch
(presumes logged into admin backend for this process)

Steps A:
1. Admin - edit demo customer (John Doe) to change password to known value, ie 'test'
2. Store - attempt to log into customer account
3. > success
4. Log out customer
5. Admin - edit customer to change email address
6. Store - attempt to log in customer with new email address
7. > failure, password mismatch
8. (can go back and change email back, and log in now works again)

Steps B:
1. Store - Log into working customer account
2. Store - Edit Account and change email, with which you have to provide the current password
3. Store - log out and try to log back in again
4. > failure, password mismatch
5. alt, trying to change the password at the same time as the email address results in the same failure

Customer password regeneration happens only when explicitly changing the password, wither through the storefront or admin-side.  Changing the email address does not trigger regen.  But, the old email address is hashed into the password creation routine, and thus tied to the old email.  Changing password seems to supercede email address changes, and thus the password is regen'd with the old email value.

Admin password routines seem unaffected by following similar procedures in the Edit User screen, as the source material upon which the password generation is built is more static in comparison, and not based on username or email.  (more particular observations not discussed here)
--test--

**Comment by timint** [comment]
Confirmed. This will be a bit pain to fix as we cannot migrate passwords. Every user would have to reset their password if we change the salt. But it needs to be fixed somehow.

**Comment by SkipperHosting** [comment]
Some thoughts:
Could not the password include some version information?  That is to say that the stored hash ('abcdef' for this example) be preceded by something like 'v2-', becoming 'v2-abcdef'.  The 'v1-' prefix added to existing values in the 2.2.0 update routine.  Then the password checking routine would know which generation method to use for comparison.
