### ISSUE TITLE
Cannot create 2 orders without closing browser

### ISSUE THREAD

**Issue by litecart-cs** [litecart/litecart#160]
What were you trying to do?
I want to create 2 orders.

What was expected to happen?
1) I create my first order
2) I create a second order

What was the actual result - what exactly did happen?
A second order is not created. The first order is overwritten.

Which LiteCart version are you running?
2.1.6

**Comment by timint** [comment]
Cannot confirm, I tried the demo.

**Comment by litecart-cs** [comment]
Strange, you can try here: https://cron.php5.cz/lc/
Maybe different server configuration (https://cron.php5.cz/info.php)?
Maybe session.auto_start?
I'll try to investigate...
