### ISSUE TITLE
printable_order_copy template in backend is still loaded from default.catalog

### ISSUE THREAD

**Issue by pabloneruda1** [litecart/litecart#161]
"template_catalog" setting is ignored for printable_order_copy template in backend
URL: .../admin/?app=orders&doc=printable_order_copy&order_id=1&media=print
the same for printable_packing_slip...

if "template_catalog" settings is changed, in backend is still loaded default template for printable_order_copy and  printable_packing_slip (from default.catalog)

v2.1.6

**Comment by dmzh22** [comment]
When the fix from timint is applied, the custom template is used

However, the CSS seems to be broken and the printable_order_copy loses all formatting.

**Comment by timint** [comment]
@dmzh22 Would this work better?

```
<?php
  document::$template = settings::get('store_template_catalog');
  document::$snippets['template_path'] = WS_DIR_APP . 'includes/templates/'. settings::get('store_template_catalog') .'/';
  document::$layout = 'printable';
```

**Comment by dmzh22** [comment]
Yes, this seems to solve the problem.
Thanks Tim!
