### ISSUE TITLE
New category picker

### ISSUE THREAD

**Issue by litecart** [litecart/litecart#163]
The category picker (see edit product) is incovenient if the merchant has a bigger list of categories. A better category picker would solve the problem. Maybe inspired by the product picker when editing order?

**Comment by litecart-cs** [comment]
https://www.jqueryscript.net/demo/Collapsible-Tree-View-Checkboxes-jQuery-hummingbird/
+ list of selected categories with a remove button
that's enough
See OpenCart or Prestashop. (but Prestashop category picker is too complicated)

**Comment by litecart** [comment]
@litecart-cs Thanks for the tip, however LiteCart aims to be as dependancy free as possible. And generating the whole tree in hidden nodes could have negative impact on performance.

**Comment by pabloneruda1** [comment]
This plugin is for inspiration only.
Of course - subcategories/sub-nodes must be loaded dynamically (via AJAX) after clicking on "+".

**Comment by litecart-cs** [comment]
This plugin is for inspiration only.
Of course - subcategories/sub-nodes must be loaded dynamically (via AJAX) after clicking on "+".

**Comment by timint** [comment]
LiteCart 2.2.4 has a new category picker for picking a single category. I am looking into rewriting the multiple category picker too as seen in edit_product.

**Comment by timint** [comment]
Closed as committed in 2.3+
