### ISSUE TITLE
Error ajax cheapest shipping

### ISSUE THREAD

**Issue by tuthanika** [litecart/litecart#169]
What were you trying to do?

What was expected to happen?

What was the actual result - what exactly did happen?

Which LiteCart version are you running?
![1](https://user-images.githubusercontent.com/22352264/70101289-0d5f1880-1667-11ea-921a-4b88369540bf.png)
![2](https://user-images.githubusercontent.com/22352264/70101290-0d5f1880-1667-11ea-8c74-33fcb7b10d73.png)
![3](https://user-images.githubusercontent.com/22352264/70101292-0df7af00-1667-11ea-8769-8415b45230e9.png)

**Comment by timint** [comment]
A description of the problem please.

**Comment by timint** [comment]
Fixed in https://github.com/litecart/litecart/commit/e8cb724b910da1b6381bf9b793ebf0f0439c61c2
