### ISSUE TITLE
GeoZone saving only the last input

### ISSUE THREAD

**Issue by demographus** [litecart/litecart#171]
I'm trying to import multiple zones at once.

When I add a zone and press the Add button for new row to appear for another zone to add it, too, when saving the change only the last input row is inserted.

I was expecting all Added zones to be imported when saving the page.

Having 3000+ zones to set up, it will take me forever to add by one -> edit zones -> add another one.

I'm currently running Litecart v2.2.0.
![geozones](https://user-images.githubusercontent.com/1465583/70868986-dd7d1280-1f8e-11ea-8aeb-36fde5c9e196.png)

**Comment by timint** [comment]
Should be fixed already in the dev branch
https://github.com/litecart/litecart/commit/2f371ad22de5a6946633fabc0daa1f98bd69ea25

**Comment by demographus** [comment]
Perfect, it really is working. Will be more careful to check all related issues already posted before starting a new one. Thank you!

**Comment by timint** [comment]
No problem. I tend to do the same. Thank you for reporting.
