### ISSUE TITLE
Terms Acceptance throwing an error on LC v2.2.0

### ISSUE THREAD

**Issue by demographus** [litecart/litecart#172]
After uploading Terms Acceptance add-on, on check-out page the following error appears:

`Warning: VQModObject::applyMod(terms_acceptance.xml) - Search not found in "": includes/templates/*.catalog/views/box_checkout_summary.inc.php(0) [SKIPPED] in ~/vqmod/vqmod.php on line 585`

I was expecting a checkbox for accepting the Terms, with a link to respective page, to be displayed.

I'm running LiteCart v2.2.0.

**Comment by timint** [comment]
Terms Acceptance is an add-on for versions prior to 2.2.0 and is not part of the core platform here on github. And it's not needed in 2.2.0. Instead go Admin -> Settings -> Legal -> Terms of Purchase.

**Comment by demographus** [comment]
Oh, thank you for pointing out.

It's just that I wasn't seeing anywhere a checkbox for accepting Terms of Purchase so I was expecting this add-on to add this functionality. Otherwise I guess I'll add to Terms of Purchase page a notice like "By navigating on this site and placing orders, you agree with the following Terms".

**Comment by demographus** [comment]
Oh, I'm sorry - didn't notice that actually when placing an order the checkbox appears!

**Comment by timint** [comment]
No problem. This is new in 2.2.0.
