### ISSUE TITLE
Edit customer pages renders password invalid

### ISSUE THREAD

**Issue by eyitee** [litecart/litecart#174]
On the **edit_account** page (v 2.2.0), if user modifies and submits the Customer Profile form , the password is inadvertently changed in the database. I found that this issue is as a result of a minor bug in the /public_html/pages/edit_account.inc.php.
The if statement below looks for a $_POST['email'] object which doesn't exist in the **Customer Profile** form, hence the _set_password_ function generates a different password (hashed by an empty string) which will obviously render the customer unable to login next time.
I resolved this by simply moving the  if statement inside the code that processes the **Sign-in & Security** form on line 44 of the same page(after the array creation code)  and everything works fine.

--line 85--
if ($customer->data['email'] != $_POST['email']) {
        $customer->set_password($_POST['password']);
      }

**Comment by timint** [comment]
Thank you for reporting. The lines at 85 can be removed.
