### ISSUE TITLE
Can't duplicate a product

### ISSUE THREAD

**Issue by ubuntuchosen** [litecart/litecart#178]
Hey. I've been a fan of LiteCart since 2016, when I stumbled on it after using OpenCart to develop my first e-commerce project. While OpenCart was pretty easy to install and configure, when I developed my second project with LiteCart, I felt a lot happier through the whole process and everything seemed even easier and more customisable than on OC. 

However, since the first time I used it, I struggled to duplicate a product. Thought it was a known issue, but searching for a solution didn't really help and since my PHP knowledge is very limited, I can't think of anything to change/update in order to make it work. 

**What were you trying to do?**
1 Open "Catalog" in admin sidebar
2 Check the checkbox on product row
3 Click "Duplicate"

**What was expected to happen?**
The product should be duplicated (new product created with the same details, but named "product 2" instead of the original "product")

**What was the actual result - what exactly did happen?**
Get error "(!) Choose category" > When category checked, get error "(!) You can't duplicate a category"

**Which LiteCart version are you running?**
I've ben struggling with this since 2.1.3 until now, including 2.2.1. (the newest available while writing this)

**Comment by timint** [comment]
Not a bug. You must select a target category to where your duplicated product should go.
