### ISSUE TITLE
Campaign % discount goes negative (and rejected) when entering a final price

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#179]
Editing a product (admin), entering a new discount campaign
Typing the final price right in the store-currency final price of the campaign, lower than the current selling price (out of any campaign)

The % discount become negative, ok...but it is rejected when saving the product

![image](https://user-images.githubusercontent.com/61077647/74584330-1f472b00-4fc9-11ea-8ee3-f7c0bee50cd4.png)

**Comment by litecart** [comment]
Make sure your store currency value is 1.00.

**Comment by timint** [comment]
Any news?

**Comment by nicolasmol** [comment]
Was my mistake, you can close.


Nicolas Molinari
Envoyé de mon iPhone
