### ISSUE TITLE
Error when all currency disabled.

### ISSUE THREAD

**Issue by szfeco** [litecart/litecart#181]
hi,
Bunch of error messages when no currency enabled

Ran into when:
 - adding a new currency
 - setting it to default
 - disabling all other currency

Workaround: set currency status to enabled (1) in mysql.

Solution would be when a currency set to default, automatically enable it, or adding new currency automatically enables it.

Cheers,
Ferenc

**Comment by litecart** [comment]
If you disable all currencies I think that it's perfectly in order that you get some sort of error.

**Comment by szfeco** [comment]
it was unintentional disabling all currencies.
By default usd and eur was there.
Added my currency and disabled the other two. Did not expect that adding a currency will be disabled by default.

**Comment by timint** [comment]
The currency must intentionally be enabled. Merchants may want to set currency prices before going live with the currency. Closing as not an error.
