### ISSUE TITLE
Class security doesn't look to be used anywhere

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#185]
2.2.2 (also checked in 2.16 and 2.2.x)
Class security doesn't look to be used anywhere...
Maybe I missed something, and this class is instanced automatically somewhere, but I tried to put a breakpoint on debugging at first line of public function init()

      self::$_bad_urls = FS_DIR_APP . 'data/bad_urls.txt';

Result: it does not look to reach here.
Tested on localhost...

**Comment by timint** [comment]
The file was removed in 2.2.0.

https://github.com/litecart/litecart/blob/9f1a9f9fd3bc148f90865484ca5c5db4f05fdf24/public_html/install/upgrade_patches/2.2.0.inc.php#L51

**Comment by nicolasmol** [comment]
ok, then, but now where is check post token ?
  function form_draw_form_begin($name='', $method='post', $action=false, $multipart=false, $parameters='') {
    return  '<form'. (($name) ? ' name="'. htmlspecialchars($name) .'"' : false) .' method="'. ((strtolower($method) == 'get') ? 'get' : 'post') .'" enctype="'. (($multipart == true) ? 'multipart/form-data' : 'application/x-www-form-urlencoded') .'" accept-charset="'. language::$selected['charset'] .'"'. (($action) ? ' action="'. htmlspecialchars($action) .'"' : '') . (($parameters) ? ' ' . $parameters : false) .'>'. PHP_EOL
          . **((strtolower($method) == 'post') ? form_draw_hidden_field('token', form::session_post_token()) . PHP_EOL : '');**
  }

**Comment by timint** [comment]
There is none. I think this piece of code can be removed.

The reason for removal is that it session post token caused too many false positives. The protection simply does not run well with today's wifi and cellular roaming. Same with the other security features. Bot trap trapped visitors with browser extensions to preload page links. The bad urls needed new urls added continusly. It simply was not worth the time spending in it.

Maybe a security bundle with come in the future as a commercial add-on. For now we're just doing it like the other platforms do it.
