### ISSUE TITLE
Geo zones limitation error

### ISSUE THREAD

**Issue by ejtipi** [litecart/litecart#187]
includes/modules/payment/pm_cod.inc.php

There is call for setting that not exist:

```
      if (!empty($this->settings['geo_zones'])) {
        if (!reference::country($country_code)->in_geo_zone($zone_code, $this->settings['geo_zones'])) return;
      }
```

...and in settings there is no key like that. There is:

`'key' => 'geo_zone_id',`

LiteCart 2.2.2

**Comment by timint** [comment]
Thanks :)
