### ISSUE TITLE
Sign up error on checkout page

### ISSUE THREAD

**Issue by domugo** [litecart/litecart#19]
I get this error on checkout page, when clicked on "sign in"

Warning: include(public_html/test/includes/templates/default.catalog/pages/login.ajax.inc.php): failed to open stream: No such file or directory in ~/includes/classes/view.inc.php on line 64
Warning: include(/public_html/test/includes/templates/default.catalog/pages/login.ajax.inc.php): failed to open stream: No such file or directory in ~/includes/classes/view.inc.php on line 64
Warning: include(): Failed opening '/public_html/test/includes/templates/default.catalog/pages/login.ajax.inc.php' for inclusion (include_path='.:/usr/local/lib/php') in ~/includes/classes/view.inc.php on line 64

Fresh install, no modifications. Latest github version.

**Comment by timint** [comment]
Latest master or latest div branch? Assuming dev (version 2 alpha) which is very experimental and under development.
