### ISSUE TITLE
Admin form Status Code: 302 Found (POST Request)

### ISSUE THREAD

**Issue by arshidkv12** [litecart/litecart#191]
What were you trying to do?
POST Request URL: http://localhost/litecart222/admin/?app=currencies&doc=edit_currency

What was expected to happen?
http://localhost/litecart222/admin/?app=currencies&doc=edit_currency 302 Status
It is redirecting to the login page. 

What was the actual result - what exactly did happen?
Add currency 

Which LiteCart version are you running?
2.2.2

**Comment by timint** [comment]
This is solved by grabbing the new lib_session.inc.php from 2.2.3.
