### ISSUE TITLE
Can't upload images to addons under "edit addon" on LiteCart site.

### ISSUE THREAD

**Issue by FuXual** [litecart/litecart#194]
I believe this is of topic from the LiteCart software, but I didn't knew where to express these problems. Thanks in advance!

What were you trying to do?
Upload add-on
What was expected to happen?
The image to be included in the addon site
What was the actual result - what exactly did happen?
It does not appear on the addon site
Which LiteCart version are you running?
LiteCart website

**Comment by timint** [comment]
This could be a .webp issue, what browser where you using?

**Comment by timint** [comment]
Closed as assuminlgy already fixed
