### ISSUE TITLE
Price formatting

### ISSUE THREAD

**Issue by ejtipi** [litecart/litecart#195]
Product page, for example https://demo.litecart.net/rubber-ducks-c-1/subcategory-c-2/yellow-duck-p-1

Product price is $18 but if you change quantity it jumps to $18.00.

**Comment by timint** [comment]
Yes the javascript money formatter does not have auto decimals (yet).

**Comment by timint** [comment]
Here is a lead if someone care to help out:

https://github.com/litecart/litecart/blob/3a4dd19c1f48d62a9025fbd1604870921b51df3b/public_html/includes/templates/default.catalog/views/box_product.inc.php#L211-L223

<?php echo settings::get('auto_decimals') ? 'remove .00' : 'leave decimals'; >
