### ISSUE TITLE
Cache error on admin access after 2.2.3 upgrade

### ISSUE THREAD

**Issue by Fritz-RT** [litecart/litecart#198]
From version 2.1.6 i have upgraded the Litecart to the latest version 2.2.3 in a testing area. The shop work fine but the admin access give me the following error:
`Deprecated: The method cache::cache_id() is deprecated, use instead cache::token() in ~/includes/library/lib_cache.inc.php (Line 60)
Warning: Invalid cache storage () in ~/includes/library/lib_cache.inc.php (Line 224)
Deprecated: The method cache::cache_id() is deprecated, use instead cache::token() in ~/includes/library/lib_cache.inc.php (Line 60)
Fatal error: Cache recorder already initiated () in ~/includes/library/lib_cache.inc.php (Line 274)`
PHP is set to 7.3. Thanks for advice to understand where I to look.

**Comment by timint** [comment]
Make sure your add-ons are up to date with 2.2.x.
Turn to the forums for support.

**Comment by Fritz-RT** [comment]
Strangely enough, without any intervention on my part, I was able to access the administration interface today without error messages!

What may have happened is a server adjustment of the policies or something similar. Something else, I really cannot imaging why an error was yesterday and no longer today. I put this testing website on a local joomla website (as subdirectory).

You can close this thread.

**Comment by timint** [comment]
:) Happy it worked out for you
