### ISSUE TITLE
can not change password

### ISSUE THREAD

**Issue by ciwind** [litecart/litecart#2]
I want to change my password, but always got the "The new password does not match the confirmed password." error.
I am sure the two items were offered same.
Please check the problem, thank you very much!

**Comment by timint** [comment]
Are you sure? Are you talking about the edit account page for customers?

I just tried it, and password changed successfully. This was my development platform though but the files should be the same.

**Comment by ciwind** [comment]
Yes, it's the edit account page on "litecart.net"(Not my owner platform). I just tried again, still the same problem.
I was going to download some add-ons, and found another problem. When I downloaded the add-on called "iDEAL Checkout", I got "dummy.zip" which includes a file named "dummy.txt". I tried with Safari and Chrome, and got the same result. So confusing...
Hope you can help, thank you 
------------------------------------------------------------------发件人：T. Almroth <notifications@github.com>发送时间：2016年8月21日(星期日) 03:48收件人：litecart/litecart <litecart@noreply.github.com>抄　送：ciwind <hijaf@aliyun.com>; Author <author@noreply.github.com>主　题：Re: [litecart/litecart] can not change password (#2)
Are you sure? Are you talking about the edit account page for customers?I just tried it, and password changed successfully. This was my development platform though but the files should be the same.—

**Comment by timint** [comment]
Oh, so it was litecart.net - not the downloadable LiteCart platform? The problem is fixed.

As for iDEAL Checkout the add-on says:

Visit the website for an updated list of supported service providers and **download the latest integration** for LiteCart. https://www.ideal-checkout.nl/plug-ins/free-plugins/litecart **(Attached here is a dummy-file)**
