### ISSUE TITLE
The field for entering a payment card is not available in the form of purchase on the website www.litecart.net  after clicking the "Confirm Order" button.

### ISSUE THREAD

**Issue by jafreg** [litecart/litecart#200]
https://www.litecart.net/en/checkout

Precondition step
User authorized on the site, have any product in basket and open page for checkout

reproduce
1 open https://www.litecart.net/en/checkout
2 input all required field of valid data
3 input "88000" to the "Postalcode" field
4 checked "I agree to the terms of purchase"
5 select "Confirm Order" button
6 Pay attention to the field to enter "Card Number" in the window of next step

Actual result: Displayed "Loading ..." in the field for entering "Card Number" in the window of the next step

Expected result: Enabled field to enter "Card Number" in the window of the next step

Additional Info: In the console browser (ex. Google Chrome v. 80.0.3987.100) i see on the parametr postal_code in "payment_method_data" function is mistake = "880002 (see to screenshot) http://prntscr.com/sncraq

**Comment by timint** [comment]
Thank you for reporting. A typo has been fixed. :)
