### ISSUE TITLE
Cart calculation issue.

### ISSUE THREAD

**Issue by farhankhan1977** [litecart/litecart#205]
What were you trying to do?

What was expected to happen?
In addition options of the products, if we add prices and uses radio button to select items with additional price, they will effect on product display, but when added into cart.

What was the actual result - what exactly did happen?
In cart it shows the actual price without addition or subtracting the price effect of the optional items.

Which LiteCart version are you running?
Tested on 2.2.3

Check on forum also,I have posted with pictures also.

**Comment by timint** [comment]
Thank you for reporting this critical issue.
An immediate release of 2.2.3.1 will be rolled out.

https://github.com/litecart/litecart/commit/12f760877e81bf13f4c4b9c5f57010859d3bbfdd

**Comment by farhankhan1977** [comment]
Now Issue for Radio Button is resolved, but issue is still there for Checkbox, like if we add option for checkbox with each item additional price, it is not working.

further to above if we want to add multiple attribute options like related to different attribute groups, it is not working, only 1 attribute group can be added in the options.

**Comment by timint** [comment]
Yes, i understood that. But I can't reproduce the error. Can you reproduce it in the demo?
https://demo.litecart.net/
