### ISSUE TITLE
Cart Summary prices

### ISSUE THREAD

**Issue by farhankhan1977** [litecart/litecart#208]
What were you trying to do?
Now Issue for Radio Button is resolved, but issue is still there for Checkbox and select option is not resolved, like if we add option for checkbox with each item additional price, it is not working.

further to above if we want to add multiple attribute options like related to different attribute groups, it is not working, only 1 attribute group can be added in the options.
What was expected to happen?

What was the actual result - what exactly did happen?

Which LiteCart version are you running?    ver2.2.3.1

**Comment by timint** [comment]
Cannot confirm an issue with price.
Can you reproduce this in the demo?
Make sure you set the price adjust for the store currency at minimum.

![image](https://user-images.githubusercontent.com/359192/84592721-13b92300-ae48-11ea-8c5b-bd1183e4c82c.png)

![image](https://user-images.githubusercontent.com/359192/84592750-377c6900-ae48-11ea-9db3-1a2541c2b029.png)

I can confirm an issue with saving a second option group. I'll be back with a solution

**Comment by timint** [comment]
Try this fix for saving more than one option groups.
https://github.com/litecart/litecart/commit/907ce18a6c2d01eaadf11e8425874e85f693a343

**Comment by farhankhan1977** [comment]
Hi support,

yes, single open selection is working, but if i need to select/checked more than 1 options which have additional prices, it prices didnt adds up.

check on demo site on yellow Duck, i have added checkbox with additional prices, if we check 1 option it works, but if we select multiple options it dont works.

reagrds,

Farhan

**Comment by timint** [comment]
Confirmed, I'm working on a fix
