### ISSUE TITLE
lib_stats.inc.php :  Capture parse time may not be at the right place

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#213]
`    public static function after_capture() {

    // Capture parse time : 
      $page_capture_time = microtime(true) - self::$_page_parse_start;
      self::set('page_capture_time', $page_capture_time);

      if (self::get('page_parse_time') > 5) {
        notices::add('warnings', sprintf(language::translate('text_long_execution_time', 'We apologize for the inconvenience that the server seems temporary overloaded right now.'), number_format($page_parse_time, 1, ',', ' ')));
        error_log('Warning: Long page execution time '. number_format($page_parse_time, 3, ',', ' ') .' s - '. $_SERVER['REQUEST_URI']);
      }
    }

    public static function before_output() {

    // Memory peak usage
      self::set('memory_peak_usage', memory_get_peak_usage(true) / 1000000);`

**Comment by timint** [comment]
Where would you want it to be?

**Comment by nicolasmol** [comment]
After_capture
Not before_output as it is currently

Nicolas Molinari
Envoyé de mon iPhone

**Comment by timint** [comment]
I think you are right. Added for a future release.
