### ISSUE TITLE
Wrong white space color

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#214]
ent_image.inc.php
line 245
`              ImageFill($_resized, 0, 0, ImageColorAllocateAlpha($_resized, $this->_whitespace[0], $this->_whitespace[0], $this->_whitespace[0], 127));`
should be
`              ImageFill($_resized, 0, 0, ImageColorAllocateAlpha($_resized, $this->_whitespace[0], $this->_whitespace[1], $this->_whitespace[2], 127));`

**Comment by timint** [comment]
Thank you :)
