### ISSUE TITLE
box_similar_products's cache should be $_GET['category_id']'s dependent

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#215]
Since, line 15
`      'categories' => isset($_GET['category_id']) ? array($_GET['category_id']) : array_keys($product->categories),`
Then
line 10 should be
`  $box_similar_products_cache_token = cache::token('box_similar_products', array($_GET['product_id'], $_GET['category_id'], 'language', 'currency'), 'file');`

**Comment by timint** [comment]
Thanks
