### ISSUE TITLE
func_image.inc.php image write path should matches the returned one

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#216]
line 68
`      if (!$image->write($options['destination'], $options['quality'], !empty($options['interlaced']))) return;`
Path into writing the image should be the same than the one returned after.
But the one after is the one resolved by realpath();
So it should be:
`      if (!$image->write(realpath($options['destination']), $options['quality'], !empty($options['interlaced']))) return;`
Or better maybe better, the following line:
`     return preg_replace('#^('. preg_quote(FS_DIR_APP, '#') .')#', '', str_replace('\\', '/', $options['destination']));`

**Comment by timint** [comment]
I don't understand, what is the issue? The entity controller supports relative paths. Is there a problem with relative paths?

**Comment by nicolasmol** [comment]
when image is written in ...realpath($options['destination'])
url should be ... realpath($options['destination'])

**Comment by timint** [comment]
Why do you need to feed the write() function with a realpath?

**Comment by nicolasmol** [comment]
Try the following I experienced:

1) Move "/cache" folder as sub folder of a new one. E .g: /data/cache/oldtype
2) Add -Option Indexes FollowSymLinks in 
.htaccess
3) Create a symbolic link /cache <=> /data/cache/oldtype

Result:
Once Image->write() will create the file, the URL used for img src in html will be for example "data/cache/oldtype/adghtrjklnnl.webp".

The link may be pointing on the file before this one is closed, leading to 404 for the img src.

Nicolas Molinari
Envoyé de mon iPhone

**Comment by timint** [comment]
What's wrong with `Alias /cache /data/cache/oldtype`?

Isn't this where your trouble is?

return preg_replace('#^('. preg_quote(FS_DIR_APP, '#') .')#', '', str_replace('\\', '/', **realpath($options['destination'])**));

Do you wish the path returned to be the symbolic path?

**Comment by nicolasmol** [comment]
﻿Simply it appears that there isn't 404 on image path while she's been written on the disk when both pathes match...have a try.
 
Chose one : real or not

Nicolas Molinari
Envoyé de mon iPhone

**Comment by timint** [comment]
I did not understand a single word of that 😆
