### ISSUE TITLE
Reference page's path

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#220]
Maybe referencing a page's path can use the same new code than categories 

`				case 'path':

          $this->_data['path'] = array($this->id => $this);

          $current = $this;
          while ($current->parent_id) {

            $this->_data['path'][$current->parent_id] = $current->parent;
            $current = $current->parent;
          }

          $this->_data['path'] = array_reverse($this->_data['path'], true);

          break;`

**Comment by timint** [comment]
Good idea. Adding it for a future release
