### ISSUE TITLE
Manufacturer image dimensions don't match with thumbnails creation 

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#221]
lines 199, 200.
Surely a copy-past
`				'viewport' => array(
					'width' => $width,
					'height' => $height,
				),`

$width and $height are not defined like this for manufacturer's image but 200x60 (400x120)
`				'thumbnail' => functions::image_thumbnail(FS_DIR_APP . 'images/' . $product->manufacturer->image, 200, 60),
				'thumbnail_2x' => functions::image_thumbnail(FS_DIR_APP . 'images/' . $product->manufacturer->image, 400, 120),`

**Comment by timint** [comment]
Thank you
