### ISSUE TITLE
Product breadcumb miss parent category

### ISSUE THREAD

**Issue by nicolasmol** [litecart/litecart#222]
I believe that in page/product.inc.php
line 55 
`		foreach (reference::category($_GET['category_id'])->path, 0, -1) as $category_crumb) {`
should be
`		foreach (reference::category($_GET['category_id'])->path as $category_crumb) {`
![image](https://user-images.githubusercontent.com/61077647/87162589-a917cd80-c2b5-11ea-9a31-71ba47f80a4f.png)

**Comment by timint** [comment]
You are absolutely right! Committed and will be pushed later.
