### ISSUE TITLE
customer unable to change the password

### ISSUE THREAD

**Issue by sakaljurgis** [litecart/litecart#229]
A small transcription error is in /public_html/pages/edit_account.inc.php on row 52:

```
if (!empty($_POST['new_password'])) {
  $customer->set_password($_POST['password']);
}
```
suggest to change to:
```
if (!empty($_POST['new_password'])) {
  $customer->set_password($_POST['new_password']);
}
```

**Comment by timint** [comment]
Well spotted! Thank you for reporting. 👍 
https://github.com/litecart/litecart/commit/a202a17624f2fd1f4a1e7454a803dbc33a984e69
