### ISSUE TITLE
Missing Column

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#23]
Fresh install Litecart-dev

// --
Granting admin access for user admin... [OK]

Set platform database version... 2.0

Patching installation with regional data... [OK]

Writing demo data...
Fatal error: 1054 - Unknown column 'mobile' in 'field list' INSERT INTO `lc_customers` (`id`, `code`, `status`, `email`, `password`, `tax_id`, `company`, `firstname`, `lastname`, `address1`, 
//--

**Comment by timint** [comment]
Demo data fixed.
Thank you for reporting.

**Comment by gabbo2** [comment]
Now we have two 'phone'

`Writing demo data...
Fatal error: 1110 - Column 'phone' specified twice INSERT INTO `lc_customers` (`i`

**Comment by timint** [comment]
You are absolutely right. The new field should be called shipping_phone, not phone. Fixed the fix :/ Thanks
