### ISSUE TITLE
order module before_process() not running

### ISSUE THREAD

**Issue by sakaljurgis** [litecart/litecart#231]
It seems that `before_process()` is actually never called (during checkout) in the `/public_html/includes/modules/mod_order.inc.php`
Where it should be added/called? Probably `litecart/public_html/pages/order_process.inc.php` right before this?
```
  // Save order
  $order->data['unread'] = true;
  $order->save();
```

**Comment by timint** [comment]
If I remember right before_process() was removed as it was unreliable. The whole idea was to throw an event before we stored the order. But many payment modules do that before this event would occcur so therefore it was unreliable. If you wanna restore it simply add these two lines before the code your quoted.

```
  $order_process = new mod_order();
  $order_process->before_process($order);
```

**Comment by timint** [comment]
https://github.com/litecart/litecart/commit/3588fc58e2da27f09dc8c75d8c51d9dead62e382
