### ISSUE TITLE
Stock option quantity problem

### ISSUE THREAD

**Issue by strpe** [litecart/litecart#234]
When ordering a product with stock option, the quantity changes only in global default item, but not in the individual option items. Tested on the clean install of Litecart 2.2.3.6
Petr

**Comment by timint** [comment]
Do you mean it doesn't subtract stock correctly?

**Comment by strpe** [comment]
It doesn't subtract correctly only for options items. I have product with two stock option. After ordering, only the number of total pieces will change. Qty of option items remains the same. You can see it in the attached picture.

![stock_option](https://user-images.githubusercontent.com/25739491/91808014-b2c20f80-ec2c-11ea-919d-7ac341c16b27.jpg)

**Comment by timint** [comment]
Confirmed! Can you see if the referenced commit solves your issue?
Big thank you for reporting!

**Comment by strpe** [comment]
Thank you Tim, commit solves this problem, stock subtract correctly.

**Comment by timint** [comment]
Very good, thank you for the confirmation. :)

**Comment by pdemaret** [comment]
I am sorry to reopen this issue, but I observe the same behavior in the latest version installed with cpanel (2.5.2). The default quantity changes, but not the options, so customers can still order items with no stock.

![Screenshot 2023-03-30 at 10 04 30](https://user-images.githubusercontent.com/12196916/228776665-675299d2-586e-4479-88b8-961c2635cc04.png)

**Comment by pdemaret** [comment]
Got it. I deleted all the options pon the product modification page, then re-created them and the problem is gone.

**Comment by timint** [comment]
Did you install 2.5.2 or did you upgrade from a lower version like 2.2.x?
Can we reproduce the problem?

**Comment by pdemaret** [comment]
Thank you for your answer. I upgraded from 2.2.9 if I remember well, using cpanel and softaculous. I cannot reproduce the problem anymore, and I think I was wrong when configuring the order status and the impact a new status would have on the stock (in this case, I wanted the stock to decrease at the order creation, because I am using litecart in a simulation).
So this behaviour is all my fault, I am afraid.
I apologise for these messages.

Thank you.

**Comment by timint** [comment]
Don't worry, not a problem. I'm just happy you think it wasn't a bug. :)
