### ISSUE TITLE
Problems clicking on a category

### ISSUE THREAD

**Issue by motoristn1** [litecart/litecart#235]
**What were you trying to do?**
When I want to click on a category it breaks somewhere

![Wolf_katalog_Spletno_naročanje](https://user-images.githubusercontent.com/70641036/91990637-43cede80-ed32-11ea-80ea-24a45304e64a.png)

**What was expected to happen?**
When I click on a category it does this to me

![narocam_si_sloshop_avto_moto_c_1_](https://user-images.githubusercontent.com/70641036/91990689-52b59100-ed32-11ea-8d17-d15fde69db96.png)

**What was the actual result - what exactly did happen?**
It does not show the page as it should
Write the following:
**Fatal error:** 1054 - Unknown column 'ag.sort' in 'field list' select cf.attribute_group_id as id, ag.sort, agi.name as name, cf.select_multiple from `narocams_lite852`.`lchi_categories_filters` cf left join `narocams_lite852`.`lchi_attribute_groups` ag on (ag.id = cf.attribute_group_id) left join `narocams_lite852`.`lchi_attribute_groups_info` agi on (agi.group_id = cf.attribute_group_id and agi.language_code = 'sl') where category_id = 1 order by priority; in ~/includes/library/lib_database.inc.php on line 254

**Which LiteCart version are you running?**
I running LiteCart® 2.2.3.6

**I didn’t change anything or add anything. He did it himself
How to solve this problem, which is not the only one.**

**Comment by timint** [comment]
You did not run the upgrade patches for 2.2.3.6?

```
ALTER TABLE `lc_attribute_groups`
ADD COLUMN `sort` ENUM('alphabetical','priority') NOT NULL DEFAULT 'alphabetical' AFTER `code`;
-- --------------------------------------------------------
UPDATE `lc_settings` SET `function` = 'zone("store_country_code")' WHERE `key` = 'store_zone_code';
-- --------------------------------------------------------
UPDATE `lc_settings` SET `function` = 'zone("store_country_code")' WHERE `key` = 'default_zone_code';
```

An upgrade or fresh install should have created it:
https://github.com/litecart/litecart/blob/dev/public_html/install/structure.sql#L4
