### ISSUE TITLE
Variable Type and Return Type Declaration

### ISSUE THREAD

**Issue by arshidkv12** [litecart/litecart#245]
I think, we can add return types and variable types. It will improve performance. What is your opinion?

**Comment by timint** [comment]
I have no idea if that's going to improve performance. Will it?
I'm thinking that's adding another instruction to the parser and should be opposite.

**Comment by arshidkv12** [comment]
Please check it https://blog.teamtreehouse.com/5-new-features-php-7

**Comment by timint** [comment]
There is no mention that type declarations would boost performance in that article. It just mentions type declaration changes as one of 5 news about PHP 7.0. The current versions of LiteCart supports 5.4 (although it should not be used).

**Comment by arshidkv12** [comment]
Ok
