### ISSUE TITLE
Price of products are displayed without tax with or without the option display price with tax

### ISSUE THREAD

**Issue by jfmss** [litecart/litecart#259]
Hello,

I'm new with Litecart 2.2.6
I give my time volunteer to help an association (local purchase on farms)

I can't display the **price with tax included** for a product when you **open a product and in the checkout**. >NOK
On the homepage for "popular products" >NOK

1/ activate the option "price display with tax included"   (Settings > Default )

2/ Open a product
     > you see the price displayed 'excluding tax'
for example https://demo.litecart.net/rubber-ducks-c-1/subcategory-c-2/yellow-duck-p-1
(issue on the DEMO website and on my website)

3/ fyi: The database is well updated with my choice (table settings >id:21)

If I change the option display price without tax > same result.
   with or without the option, the display stay the same

I don't know the structure of Litecart.
Can you guide me to which files I could search?
with maybe some info: where are the CLASS,... ?

Thanks for your help
jf
![litecart_tax_display](https://user-images.githubusercontent.com/77468830/104784322-5816f380-5788-11eb-8663-45d3197ce951.JPG)

**Comment by timint** [comment]
You were granted a support ticket, yet you created an issue ticket instead.

**Comment by jfmss** [comment]
Hello, 
This issue come from a problem with the store currency option (Settings > Store option) 
It's not a problem with TAX 
Sorry for this inconvenient
I close this
