### ISSUE TITLE
Possible typo in default.catalog/config.inc.php ?

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#26]
Code begin with ':' ?

`
      'title' => language::translate(__CLASS__.':title_product_modal_window', 'Product Modal Window'),
      'description' => language::translate(__CLASS__.':description_product_modal_window', 'Enables or disables 
      'title' => language::translate(__CLASS__.':title_sidebar_parallax_effect', 'Sidebar Parallax Effect'),
      'description' => language::translate(__CLASS__.':description_sidebar_parallax_effect', 'Enables or disables 
`

**Comment by timint** [comment]
Confirmed. Thank you for reporting.
Don't forget to mention which file you are refering to.
