### ISSUE TITLE
label:enhacement cart: increase / decrease quantity automatic update

### ISSUE THREAD

**Issue by xavierve** [litecart/litecart#260]
What were you trying to do?
in the cart, I try to increase the product quantity's product ordered,, so I press "+"
What was expected to happen?
As a potential client, I supose the quantity being updated
What was the actual result - what exactly did happen?
Quantity is not updated until I clic on update button
Can you add some JS to allow quantity being auto updated? think is a must for mobile usability
thanks!

**Comment by timint** [comment]
Dude. What do you think the purpose of that button is?

**Comment by xavierve** [comment]
Sorry, I'm affraid I didn't explain me good enaught.
What I mean is: Why not making the Update button disapear? 
Using JS to detect the change and auto update subtotal. 
So, when the User increases the product quantity, then the amount is populated automatically. (Maybe form's SELECT  property can be better for detecting the change and finger usability)
Hope I am more clair now. Thanks for hearing and reply 👍

**Comment by timint** [comment]
Having an input event update and refresh the checkout components. You are forgetting this is a chain reaction.

Let's say you have 1 quantity and decide to step it up to 5. Each tick fires 4 additional requests. So until you reach 5 you fired off 16 ajax queries.

One way would be having a timeout event. But I just haven't bothered.

**Comment by xavierve** [comment]
hey! thanks for reply.
Jumping one by one it's bad also for usability, thats why I've mentioned the SELECT tag,. 
Could it be that way?

**Comment by timint** [comment]
Closing as unlikely to implement to core platform. Addons welcome.
