### ISSUE TITLE
product price is empty for currency decimals = 0

### ISSUE THREAD

**Issue by litecart-cs** [litecart/litecart#261]
What were you trying to do?
- I set currency XXX with decimals = 0
- I set product price 200 XXX

What was expected to happen?
- saving product price = 200 XXX
 
What was the actual result - what exactly did happen?
- after saving price is the price field empty

Which LiteCart version are you running?
- last version 2.2.7 (tested on the demo.litecart.net)

**Comment by litecart-cs** [comment]
From demo.litecart.net - probable cause: HTML element value="200."
`<input class="form-control" type="number" step="any" name="prices[USD]" value="200." data-type="currency" data-currency-price="" placeholder="">`

**Comment by timint** [comment]
This should have been resolved. Can you confirm the problem is not there with 2.3.1?
