### ISSUE TITLE
installation error v2.2.8 - DB_DATABASE_CHARSET vs. DATABASE_CHARSET

### ISSUE THREAD

**Issue by litecart-cs** [litecart/litecart#263]
There is problem:
'{DATABASE_CHARSET}' => 'utf8' is missing:
https://github.com/litecart/litecart/blob/cc3528b93c0aadc329e0c4842f24517715172c7b/public_html/install/install.php#L307

result:
> Fatal error: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '{DATABASE_CHARSET} COLLATE utf8_czech_ci' at line 9 CREATE TABLE IF NOT EXISTS `v228_attribute_groups` ( `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, `code` VARCHAR(32) NOT NULL DEFAULT '', `sort` ENUM('alphabetical','priority') NOT NULL DEFAULT 'alphabetical', `date_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `code` (`code`) ) ENGINE=MyISAM DEFAULT CHARSET={DATABASE_CHARSET} COLLATE utf8_czech_ci;

**Comment by litecart-cs** [comment]
There is problem:
'{DATABASE_CHARSET}' => 'utf8' is missing:
https://github.com/litecart/litecart/blob/cc3528b93c0aadc329e0c4842f24517715172c7b/public_html/install/install.php#L307

**Comment by timint** [comment]
Thank you I can confirm an issue and here is the fix.
https://github.com/litecart/litecart/commit/88100605ccdb8371dd06cee72ca20de41c4a15e8
