### ISSUE TITLE
Incorrect table name 

### ISSUE THREAD

**Issue by Nacho-AT** [litecart/litecart#264]
Hi,
I have detected an error in /catalog.app/csv.inc.php. The name of the INFO table of Products.
DB_TABLE_PRODUCTS ."_info 
must be:
DB_TABLE_PRODUCTS_INFO

https://github.com/litecart/litecart/blob/3171f449d31d1be177c8642cd9ff76f6f84f3eba/public_html/admin/catalog.app/csv.inc.php#L390

**Comment by timint** [comment]
Thanks, should not impact functionality but has been fixed.

**Comment by Nacho-AT** [comment]
> Thanks, should not impact functionality but has been fixed.

Thank you Tim.
It did affect functionality because the table definition constant includes the "quotation mark" (`LC_PRODUCTS`_info), so importing CSV data caused a fatal error.

**Comment by timint** [comment]
Ooh you are right. Thank you for reporting.
