### ISSUE TITLE
Creating a new buy option in a product

### ISSUE THREAD

**Issue by DeannahPaty** [litecart/litecart#265]
I was creating a new buy option in a product and when I try to save it does not save and sends this error message:
Notice: Undefined index: pt in ~/admin123/catalog.app/edit_product.inc.php on line 749

all of the others option (all the same)  worked fine, this is only one more option but it doesn't let me creat it.. if I delete some options it let me do it.. so it's not an error on the options itself, but something to do with limits? 

(sorry about my english I'm Portuguese)

thank you all

**Comment by timint** [comment]
Can this be reproduced in the demo?
https://demo.litecart.net/

**Comment by timint** [comment]
Closing as not enough feedback.
Probable cause missing option translation.
