### ISSUE TITLE
No working link customer service in version 2.2.9

### ISSUE THREAD

**Issue by DanielS1983** [litecart/litecart#266]
What were you trying to do?
upgrade from version 2.2.8 to 2.2.9

What was expected to happen?
An upgrade to my site

What was the actual result - what exactly did happen?
The link to customer service no longer worked.

Which LiteCart version are you running?
now 2.2.8 again because 2.2.9 doesn't work for me

**Comment by timint** [comment]
Already fixed. https://github.com/litecart/litecart/commit/6ead4546a1eb068cdc61f42b4689805721164556
Keep in mind 2.2.9 is still a development release
