### ISSUE TITLE
price calculation display wrong 2.2.9

### ISSUE THREAD

**Issue by DanielS1983** [litecart/litecart#268]
I have just upgraded from 2.2.8 to 2.2.9 and find out that the prices with tax are not right.

It goes wrong with the calculation of the TAX. He calculates the price 2x the percentage for the price including tax.

For example, € 100 + high (21 percent) becomes € 142.

**Comment by timint** [comment]
Are you sure LiteCart is a he? 😄
Was this issue ticket invalid?

**Comment by DanielS1983** [comment]
He or she... no idea but I like it ;)Yes the ticket is unnecessary. I discovered a mistake in the price when updating, but I made that mistake myself by placing countries 2x in a geo zone. Sorry for creating the ticketKind regards, Daniël Op 20 mrt. 2021 16:19 schreef "T. Almroth" ***@***.***>:

Are you sure LiteCart is a he? 😄

Was this issue ticket invalid?
