### ISSUE TITLE
No predefined charset mapped for Windows locale

### ISSUE THREAD

**Issue by xmexpi** [litecart/litecart#271]
What were you trying to do?
Install litecart on my localhost using MAMP
What was expected to happen?

What was the actual result - what exactly did happen?

Error Notice: No predefined charset mapped for Windows locale en_US.utf8. Attempting automatic detection instead. in ~/includes/library/lib_language.inc.php on line 313

On admin dashboard it only shows error on localhost installation on shared hosting is fine.

Which LiteCart version are you running?
2.2.9

**Comment by timint** [comment]
Use a windows locale for a windows machine, e.g. en-US, english or eng.
