### ISSUE TITLE
Notice: Array to string conversion in ~/includes/references/ref_country.inc.php on line 108

### ISSUE THREAD

**Issue by stojanpetkovic** [litecart/litecart#276]
When I in module cash on delivery choose Geo zone limit option, for example European Union, on the checkout page I have this error
Notice: Array to string conversion in ~/includes/references/ref_country.inc.php on line 108

If is my choose empty, than I don't have error.

I using LiteCart® 2.3.1
Error is on the pictures
[PIC1](https://koznaobuca.com/images/Picture%201.jpg)
[PIC2](https://koznaobuca.com/images/Picture%202.jpg)

Can anybody help with this error
Thank you
Stojan

**Comment by timint** [comment]
This is related to specific add-ons and is discussed here
https://www.litecart.net/sv/addons/166/stripe-card-payment/topics/16001/array-to-string-conversion-in-payment-module
