### ISSUE TITLE
PHP Error in "/admin/?app=countries&doc=countries"

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#28]
in /admin/?app=countries&doc=countries (v2a)

If disable all countries and save PHP says:

Notice: Undefined offset: 0 in ~/includes/library/lib_customer.inc.php on line 152
Warning: Passed argument cannot be empty in ~/includes/library/lib_reference.inc.php on line 38
Warning: Passed argument cannot be empty in ~/includes/library/lib_reference.inc.php on line 38

Could be a message instead, like "You must at least enable one country" :-)

**Comment by gabbo2** [comment]
OR "You cannot disable the default country"

**Comment by timint** [comment]
Excellent feedback. Thank you for reporting!
