### ISSUE TITLE
MyISAM Table Space Storage Prevents Database Encryption At Rest

### ISSUE THREAD

**Issue by mishfit** [litecart/litecart#284]
## What were you trying to do?
Encrypt the database at rest
## What was expected to happen?
All table spaces would be encrypted.
## What was the actual result - what exactly did happen?
The table spaces were not encrypted because they use the `MyISAM` storage engine.
## Which LiteCart version are you running?
2.3.5

Before creating a pull request to swap out the `MyISAM` storage engine for `InnoDB` I wanted to ask if you knew any negative implications of doing so. Essentially, why are you using `MyISAM` over `InnoDB`? If it's just a relic of historical context or if it is a good thing to do today.

**Comment by timint** [comment]
Actually LiteCart prefers Aria over MyISAM during installation. If Aria (MariaDB) is not present it will fall back to MyISAM.
The reason Aria/MyISAM is preferred over InnoDB is tests showed better performance.

But a lot has happened with performance during the years and LiteCart 3.0 will defaullt to InnoDB.

**Comment by timint** [comment]
Closing as already committed to 3.0
