### ISSUE TITLE
Warning: Undefined variable $local_file in [...]/litecart/install/install.php on line 210

### ISSUE THREAD

**Issue by Wachhund** [litecart/litecart#285]
https://github.com/litecart/litecart/blob/e018878e058e2886615d1722b5189efa08c01cce/public_html/install/install.php#L210
https://github.com/litecart/litecart/blob/e018878e058e2886615d1722b5189efa08c01cce/public_html/install/install.php#L211

**Comment by Wachhund** [comment]
A possible fix:
$local_file => $file

**Comment by timint** [comment]
Thank you :)
