### ISSUE TITLE
Framework Styles Differ in LESS and CSS

### ISSUE THREAD

**Issue by mishfit** [litecart/litecart#287]
### What were you trying to do?
Use the Developer Kit
### What was expected to happen?
The generated CSS would match CSS in a non-Developer Kit environment
### What was the actual result - what exactly did happen?
The generated CSS differed
### Which LiteCart version are you running?
2.4.0

When running the developer kit there are differences as a result of these files differing:
[framework.css](https://github.com/litecart/litecart/blob/dev/public_html/includes/templates/default.catalog/css/framework.css#L1377)
```
.loader {
  display: inline-block;
  background: url('../images/loader.svg');
  background-size: cover;
  animation-name: spin;
  animation-duration: 2000ms;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}
```
and 
[loader.less](https://github.com/litecart/litecart/blob/dev/public_html/includes/templates/default.catalog/less/framework/loader.less)
```
.loader {
  display: inline-block;
  background: url('../../images/loader.svg'); // IE 11 (Requires the property preserveAspectRatio="none slice")
  background-size: cover;
  animation-name: spin;
  animation-duration: 2000ms;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}
```
specifically, the loader image's relative location.

**Comment by timint** [comment]
I think this is a problem with the Developer Kit. The less files renders fine with the Grunt contributions (package.json).
There has been some troubles with the Developer Kit recently since I introduced CSS variables. Let me know if you find a solution.

**Comment by mishfit** [comment]
Good to know, I simply opted to remove the developer kit from our staging environment and generate in CI before deploying to the server.
