### ISSUE TITLE
Order copy recipients dosent arrive on mail

### ISSUE THREAD

**Issue by lipici** [litecart/litecart#288]
What were you trying to do? 
Im doing an order on my site

What was expected to happen? 
After i send the order to receive a copy recipients on mail from i choosed in settings checkout / send order confirmation is set as true

What was the actual result - what exactly did happen?
 I never receive a mail and i dont know when someone makes an order on my site

Which LiteCart version are you running?
 Last one

**Comment by timint** [comment]
I can confirm the BCC is not delivered when using PHP mail() instead of SMTP.
The email to the customer is delivered.

I checked the headers sent to mail() and they do state a Bcc:

```
Date: Thu, 26 May 2022 18:56:37 +0200
From: My Store <demo@litecart.net>
Sender: My Store <demo@litecart.net>
Reply-Return-Path: demo@litecart.net
MIME-Version: 1.0
X-Mailer: LiteCart/2.4.0
X-Sender: My Store <demo@litecart.net>
Bcc: copy@litecart.net
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit"
```

So I have no idea why this doesn't work.

**Comment by timint** [comment]
I figured it out. Grab the new file includes/entities/ent_email.inc.php and drop on top of your current.

**Comment by lipici** [comment]
Thank you. I tested and its working.
