### ISSUE TITLE
PHP notice on orders (v2a)

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#30]
1. Disable USD in admin->currencies
2. Go to admin->order (and other places) 

Notice: Undefined index: USD in ~/includes/library/lib_currency.inc.php on line 171
Notice: Undefined index: USD in ~/includes/library/lib_currency.inc.php on line 174
Notice: Undefined index: USD in ~/includes/library/lib_currency.inc.php on line 174

**Comment by timint** [comment]
This is not a bug, if you disable a currency that order history is depending on - you will get trouble. What was expected to happen instead?

**Comment by gabbo2** [comment]
At least a warning when delete/disable depending curency :-)
