### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Ax-o** [litecart/litecart#308]
### What where you trying to do?
Access Product page or client area

### What actually happened?
Server Error. I think its not generating the page

### What did you expect to happen?
See the product page or the client area

### LiteCart Version

LiteCart 2.5.1

### PHP Version

PHP 8.1.2-1ubuntu2.9

### Error/Backtrace

```shell
The requested URL was not found on this server.

Apache/2.4.52 (Ubuntu) Server at XXX.XXX.XXX Port 80
```

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

I don't know

### If this problem could be related to a browser. Which one?

None

**Comment by timint** [comment]
Is this an installation on your computer or server?
It sounds like a mod_rewrite, .htaccess RewriteBase or document root problem.

https://www.litecart.net/forums/topic?topic_id=7951

Come start a new thread and talk to us in the forums.
https://www.litecart.net/forums/
