### ISSUE TITLE
Typo in variable.css

### ISSUE THREAD

**Issue by apps4research** [litecart/litecart#314]
### Description

found a typo in variable.css

 --card-footer-**backgorund**-color: #f2f3f6;

should read

 --card-footer-background-color: #f2f3f6;

### LiteCart Version

LiteCart 2.5.3

### PHP Version

PHP 8.1

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

I don't know

### If this problem could be related to a browser. Which one?

Not relevant

**Comment by timint** [comment]
Patched, thank you for reporting :)
