### ISSUE TITLE
Correction of the iron box (RTL)

### ISSUE THREAD

**Issue by aljailane** [litecart/litecart#315]
### Description

In the selection box, the directional sign covers the text of the box
In languages from right to left the icon is reflected

BOX ICON NO LEFT
https://prnt.sc/7JGexo3LnK-f

ICON NO LEFT
https://prnt.sc/nmc5L80nz8ga

NO RTL
https://prnt.sc/p94xq66uRBdM

### LiteCart Version

ALL

### PHP Version

ALL

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

None

### If this problem could be related to a browser. Which one?

None

**Comment by timint** [comment]
Thank you, I forgot there was an issue ticket. Commits referenced are the following:
https://github.com/litecart/litecart/commit/97e147939f19f2a01644918f57cb5c8624851f98
https://github.com/litecart/litecart/commit/dd7556da90c77a6da94f13dc030be0484b330814
