### ISSUE TITLE
.webp images aren't processed correctly

### ISSUE THREAD

**Issue by HdTahnoon** [litecart/litecart#324]
### What where you trying to do?
Trying to upload images that are using the .webp extension for products 

### What actually happened?
Seems like whatever processes the files is not able to read it as "image"

### What did you expect to happen?
Successful upload of images

Figured it out by changing the same images to a .jpg format and uploading again successfully.

### LiteCart Version

LiteCart 2.5.4

### PHP Version

PHP 8.1.16

### Error/Backtrace

```shell
unable to open file `/tmp/magick-3132943Shi0EhzzGtY1': No such file or directory @ error/constitute.c/ReadImage/604
```

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

I don't know

### If this problem could be related to a browser. Which one?

Chrome

**Comment by timint** [comment]
This is not a bug. Your web server lacks the webp library for imagick or was compiled with webp disabled.

**Comment by HdTahnoon** [comment]
> 

Understood, sorry for the confusion.

**Comment by timint** [comment]
No problem. :) I know this as this error is quite common on servers.
