### ISSUE TITLE
Wont print packing slip or order

### ISSUE THREAD

**Issue by solarsurfer123** [litecart/litecart#328]
### What where you trying to do?
Won't print packing slip or order, comes up with file not found error 404.
<img width="829" alt="Screenshot 2023-12-09 073126" src="https://github.com/litecart/litecart/assets/153351579/617cf019-3d6b-49de-bb6f-167eebaba21e">
#
#
### LiteCart Version

2.5.4

### PHP Version

PHP 8.1 and PHP 7.4

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

No

### If this problem could be related to a browser. Which one?

Not relevant

**Comment by solarsurfer123** [comment]
This now works after producing a default fake order, so you can ignore this now, thanks anyways
Regards

**Comment by timint** [comment]
Was the order you were trying to open in a certain state that could explain the problem?

A missing order id or public key in the URL will produce a 404 error.
https://github.com/litecart/litecart/blob/86a1277cacfab45f71b98da445de9b8ade4e7fa5/public_html/pages/printable_order_copy.inc.php#L18
