### ISSUE TITLE
MariaDB is yet not compatible and an error is return durring installaltion

### ISSUE THREAD

**Issue by Lathanao** [litecart/litecart#337]
### What where you trying to do?
I follow instruction from install page: https://github.com/litecart/installer/tree/master/cli
And did this command: "
```
bash -c "$(curl https://raw.githubusercontent.com/litecart/installer/master/cli/install.sh)"
```

### What actually happened?
![image](https://github.com/litecart/litecart/assets/6756795/19a2adfd-d573-4d68-90f4-ca2f5184aaf9)

### What did you expect to happen?
Getting a smooth installation.

### LiteCart Version

Idk, latest maybe?

### PHP Version

PHP8.x

### Error/Backtrace

```shell
The error is:

mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
ERROR 2002 (HY000): Can't connect to server on '127.0.0.1' (115)
```
```


### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

None

### If this problem could be related to a browser. Which one?

Chrome

**Comment by timint** [comment]
MariaDB is compatible but this is a heads up warning it will not be in a future version. They will stop supporting the filename mysql to be a drop in replacement.

Meaning you can still use the installer. But we will have to change this by time.

**Comment by Lathanao** [comment]
This is what I did and it worked. 
Thank.

**Comment by timint** [comment]
I am reopening this as a reminder to add support future mariadb releases.

**Comment by timint** [comment]
CLI installer now checking for mariadb first.
https://github.com/litecart/installer
