### ISSUE TITLE
When install by CLI, the default admin password is empty

### ISSUE THREAD

**Issue by Lathanao** [litecart/litecart#338]
### What where you trying to do?

$ bash -c "$(curl https://raw.githubusercontent.com/litecart/installer/master/cli/install.sh)"

But I debug with"
$ cd ./install
$ php ./install.php \     
 --document_root="/home/hello/PHPPlayground/litecart" \
  --db_server=127.0.0.1 \
  --db_database=litecart1 \
  --db_username=Yomaria \
  --db_password=hahaha \
  --db_prefix=lc_ \
  --db_collation=utf8mb4_swedish_ci \
  --country=US \
  --timezone=Asia/Bangkok \
  --admin_folder=admin \
  --admin_username=admin \
  --admin_password=admin123 \
  --development_type=standard

### What actually happened?
Line 447 in install/install.php
[...] password_hash($_REQUEST['password'], PASSWORD_DEFAULT)) [...]

But $_REQUEST['password'] is empty.
So, the password set for the first admin is an empty string. 

### LiteCart Version

LiteCart 2.5.5

### PHP Version

PHP 8.1

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

None

### If this problem could be related to a browser. Which one?

None

**Comment by timint** [comment]
Can't confirm
https://github.com/litecart/litecart/blob/f850249914c8c936b94672069e75682dbe8805d2/public_html/install/install.php#L27-L32
https://github.com/litecart/litecart/blob/f850249914c8c936b94672069e75682dbe8805d2/public_html/install/install.php#L433

But your multiline command is missing the ending \

```
php ./install.php \
--document_root="/home/hello/PHPPlayground/litecart" \
--db_server=127.0.0.1 \
--db_database=litecart1 \
--db_username=Yomaria \
--db_password=hahaha \
--db_prefix=lc_ \
--db_collation=utf8mb4_swedish_ci \
--country=US \
--timezone=Asia/Bangkok \
--admin_folder=admin \
--admin_username=admin \
--admin_password=admin123 \
--development_type=standard
```
