### ISSUE TITLE
Undefined variable $errors 

### ISSUE THREAD

**Issue by s22-tech** [litecart/litecart#340]
### Description

Error Log
`Warning: Undefined variable $errors in ~/includes/templates/default.admin/pages/about.inc.php on line 223`

### LiteCart Version

latest dev version

### PHP Version

PHP 8.3

### Is this a problem that can be reproduced in the demo platform (https://demo.litecart.net/admin)?

None

### If this a visual problem that could be related to a browser. Which one?

None

**Comment by timint** [comment]
There is no trace of $errors on line 223
https://github.com/litecart/litecart/blob/dev/public_html/admin/about.php#L223

**Comment by s22-tech** [comment]
> There is no trace of $errors on line 223 https://github.com/litecart/litecart/blob/dev/public_html/admin/about.php#L223

Wrong "about" page. 😉

https://github.com/litecart/litecart/blob/d16cdda55398b933b8dca8db190d56f144f4b324/public_html/includes/templates/default.admin/pages/about.inc.php#L224

**Comment by timint** [comment]
🤦‍♂️
But that was unexpected.
https://github.com/litecart/litecart/blob/dev/public_html/admin/about.php#L267
https://github.com/litecart/litecart/blob/dev/public_html/includes/templates/default.admin/pages/about.inc.php#L224

**Comment by s22-tech** [comment]
I must have gotten ahold of an old version, so that solves that problem.  But shouldn't line 220 

https://github.com/litecart/litecart/blob/d16cdda55398b933b8dca8db190d56f144f4b324/public_html/admin/about.php#L220

have only a single glob, i.e.:

`foreach (functions::file_search(FS_DIR_STORAGE . 'logs/*.log') as $file) {`

Having two of them doesn't work on my install.

**Comment by s22-tech** [comment]
Everything works as expected now.  Thanks.
