### ISSUE TITLE
Registration Issue: No Email Verification Code Sent and Contact Form Not Working

### ISSUE THREAD

**Issue by scriptinker** [litecart/litecart#341]
### What where you trying to do?

I was trying to register a new account on LiteCart. After registering, I expected to receive an email verification code to complete the account setup. Additionally, when I encountered issues with the verification email, I tried to use the contact form to report the problem.

### What actually happened?

After registering, the system displayed a message indicating that a verification code was sent to my email. However, I never received the verification code, despite trying with different email accounts and browsers. Furthermore, the contact form did not work, and I was unable to send a message to report the issue.

### What did you expect to happen?

I expected to receive the verification code immediately after registering so that I could verify my email and complete the account setup. I also expected the contact form to function properly, allowing me to report any issues I encountered.

### LiteCart Version

Litecart

### PHP Version

PHP

### Is this a problem that can be reproduced in the demo platform (https://demo.litecart.net/admin)?

None

### If this a visual problem that could be related to a browser. Which one?

None

**Comment by timint** [comment]
Thank you, confirmed and resolved. 🙂
