### ISSUE TITLE
cashfree payment intragtion

### ISSUE THREAD

**Issue by developerakashoffical** [litecart/litecart#343]
### What where you trying to do?
i am intragtion to payment gatway and crate casf free payment gatway then incert the code  Cashfree order token not found in session.

<?php

class pm_cashfree {

  public $id = __CLASS__;
  public $name = 'Cashfree Payment Gateway';
  public $description = 'Cashfree integration for LiteCart';
  public $author = 'ACME Corp.';
  public $version = '1.0';
  public $website = 'https://www.cashfree.com';
  public $priority = 1;

  private $app_id = ''; // App ID
  private $secret_key = ''; // Secret Key

  // This method returns available payment options at checkout.
  public function options($items, $subtotal, $tax, $currency_code, $customer) {
    if (empty($this->settings['status'])) return; // Disable if not active

    return [
      'title' => 'Cashfree Payment',
      'options' => [
        [
          'id' => 'cashfree',
          'icon' => 'images/payment/cashfree.png',
          'name' => 'Pay via Cashfree',
          'description' => 'Secure payment via Cashfree.',
          'fields' => '',
          'cost' => 0,
          'tax_class_id' => 0,
          'confirm' => 'Pay Now',
        ],
      ]
    ];
  }

  // Initiate transfer to Cashfree's payment gateway.
  public function transfer($order) {
    try {
      $client = new wrap_http();

      // Create request body for Cashfree
      $request = [
        'order_id' => $order->data['id'],
        'order_amount' => $order->data['total'],
        'order_currency' => $order->data['currency_code'],
        'customer_details' => [
          'customer_id' => $order->data['customer']['id'],
          'customer_email' => $order->data['customer']['email'],
          'customer_phone' => $order->data['customer']['phone'],
        ],
        'return_url' => document::ilink('order_process'),
        'notify_url' => document::link(WS_DIR_APP . 'ext/cashfree/callback.php', ['order_id' => $order->data['id']]),
      ];

      // Set request headers
      $headers = [
        'x-client-id' => $this->app_id,
        'x-secret-key' => $this->secret_key,
        'Content-Type' => 'application/json'
      ];

      // Send request to Cashfree API
      $response = $client->call('POST', 'https://api.cashfree.com/api/v1/order', json_encode($request), $headers);

      // Handle the response
      $result = json_decode($response, true);

      if (!$result || isset($result['error'])) {
        throw new Exception('Error during payment creation: ' . ($result['error'] ?? 'Unknown error'));
      }

      // Redirect to Cashfree payment gateway
      return [
        'action' => $result['payment_link'],
        'method' => 'GET',
        'fields' => []
      ];

    } catch (Exception $e) {
      return ['error' => $e->getMessage()];
    }
  }

  // Verify payment response after order processing
  public function verify($order) {
    try {
      $client = new wrap_http();

      // Check if session data for "cashfree" exists before trying to access it
      if (!isset(session::$data['cashfree']['order_id'])) {
        throw new Exception('Cashfree order ID not found in session.');
      }

      // Make a GET request to verify the transaction
      $response = $client->call('GET', 'https://api.cashfree.com/api/v1/order/' . session::$data['cashfree']['order_id'] . '/verify', [], [
        'x-client-id' => $this->app_id,
        'x-secret-key' => $this->secret_key,
      ]);

      $result = json_decode($response, true);

      if (!$result || isset($result['error'])) {
        throw new Exception('Verification failed: ' . ($result['error'] ?? 'Unknown error'));
      }

      return [
        'order_status_id' => $this->settings['order_status_id'],
        'transaction_id' => $result['transaction_id'],
        'payment_terms' => 'PWO',
        'comments' => 'Payment successfully verified via Cashfree.',
      ];

    } catch (Exception $e) {
      return ['error' => $e->getMessage()];
    }
  }

  // Settings for module
  public function settings() {
    return [
      [
        'key' => 'status',
        'default_value' => '1',
        'title' => 'Enable Cashfree Payment',
        'description' => 'Toggle Cashfree as a payment option.',
        'function' => 'toggle("e/d")',
      ],
      [
        'key' => 'order_status_id',
        'default_value' => '0',
        'title' => 'Order Status:',
        'description' => 'Set the status for successful payments.',
        'function' => 'order_status()',
      ],
    ];
  }

  // Callback handler after successful payment
  public function callback($order) {
    try {
      // Check for order and perform any required post-payment actions
    } catch (Exception $e) {
      http_response_code(400);
      echo $e->getMessage();
    }
  }
}

### What actually happened?
show the problam  Cashfree order token not found in session.

### What did you expect to happen?
kindly slove the problam 

### LiteCart Version

2.5.5

### PHP Version

8.1

### Is this a problem that can be reproduced in the demo platform (https://demo.litecart.net/admin)?

None

### If this a visual problem that could be related to a browser. Which one?

None

**Comment by timint** [comment]
Seriously?

**Comment by developerakashoffical** [comment]
Yes sir kindly help me sir slove the problem

**Comment by timint** [comment]
I'm not even gonna try to interpret this
![image](https://github.com/user-attachments/assets/b0604446-6842-49a0-8247-e37d4c7671c8)
