### ISSUE TITLE
Payment Validation Error: Missing order id

### ISSUE THREAD

**Issue by fjfmaster** [litecart/litecart#345]
### What where you trying to do?
I installed LiteCart and the Square payment module.

### What actually happened?
The orders are documented under orders in the LiteCart shop interface but, Payment doesn't process because of a "missing order ID".   I looked for an order module and have no idea if that's what I'm missing or if it's something ini the Square payment module setup.  This has occured on ALL order attempts since going into a production mode.

### What did you expect to happen?
The order and Payment to process.

### LiteCart Version

LiteCart - Installed in September.... Don't know how to get the ver.

### PHP Version

PHP 7.4 (ea-php74)   - 8.1 is available

### Error/Backtrace

```shell
Payment Validation Error: Missing order id is posted in the order detail.
```

### Is this a problem that can be reproduced in the demo platform (https://demo.litecart.net/admin)?

I don't know

### If this a visual problem that could be related to a browser. Which one?

None

**Comment by timint** [comment]
This is the repository for the core platform of LiteCart.
Third party or community support for addons are in the forums.
https://www.litecart.net/en/addons/587/square/topics/
