### ISSUE TITLE
Error in modules (v2b)

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#38]
Admin > Modules > Job Modules
1. Install error reporter and save
2. Press "Run now"
3. Go back to Job Modules and edit module
--
Fatal error:  Cannot use object of type ctrl_module as array in /var/www/litecart2/admin/modules.app/edit_module.inc.php on line 125

**Comment by timint** [comment]
Was this not solved with the patch?
https://github.com/litecart/litecart/commit/c4fd3db5e1edf6c41d11e2154cfbd24ea5759f6b

**Comment by gabbo2** [comment]
This is new error..

**Comment by timint** [comment]
Unable to verify it

**Comment by timint** [comment]
Confirmed and patched! Thank you for the mail instructions how to simulate the issue.
