### ISSUE TITLE
CSV Export (v2b)

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#39]
CSV Export (to screen)
Caregories:
Lots of this..
<strong>Warning:</strong> Illegal string offset 'en' in <strong>~/admin/catalog.app/csv.inc.php</strong> on line <strong>27</strong><br />
<strong>Notice:</strong> Uninitialized string offset: 0 in <strong>~/admin/catalog.app/csv.inc.php</strong> on line <strong>27</strong><br />
--
Products:
Fatal error: Cannot use object of type ref_manufacturer as array in /var/www/litecart2/admin/catalog.app/csv.inc.php on line 194
--

**Comment by gabbo2** [comment]
Oops, errortext contains strong-tags :-)

**Comment by timint** [comment]
Thanks this error was inherited from the rewriting of ref_product.
