### ISSUE TITLE
payment_due not correct value

### ISSUE THREAD

**Issue by AntonTro** [litecart/litecart#43]
in ctrl_order.inc.php on line 437:
` if (!empty($order_total['calculate'])) `

should be 
`if (!empty($order_total['calculate']) &&  $order_total['calculate'] == 1 ) `

Otherwise it add the subtotal to the payment_due and does not add the payment alternative fee.

Version 2.0

**Comment by timint** [comment]
Why the == 1. The value expected is 1/0 or true/false. 2, 3, 4, -1 is not expected.

http://php.net/manual/en/function.empty.php
