### ISSUE TITLE
CSS issue Internet Explorer 11 / Windows 7

### ISSUE THREAD

**Issue by timint** [litecart/litecart#48]
Reported by Luka:

![image](https://cloud.githubusercontent.com/assets/359192/24579790/2dd270ac-16fc-11e7-9173-0a58b3bceb4e.png)

(Working in IE 11 on Windows 10)

**Comment by litecart** [comment]
Fix solves problem in IE11 on Windows 10. Have not confirmed Windows 7.
Thank you for reporting.
