### ISSUE TITLE
Upgrade form 1.3.5 to 1.3.6 Problem

### ISSUE THREAD

**Issue by netsajt** [litecart/litecart#5]
Warning: array_keys() expects parameter 1 to be array, null given in ~/netsajt/orders.app/edit_order.inc.php on line 12
Warning: Invalid argument supplied for foreach() in ~/netsajt/orders.app/edit_order.inc.php on line 12
Warning: array_keys() expects parameter 1 to be array, null given in ~/netsajt/orders.app/edit_order.inc.php on line 16
Warning: Invalid argument supplied for foreach() in ~/netsajt/orders.app/edit_order.inc.php on line 16
Warning: Invalid argument supplied for foreach() in ~/netsajt/orders.app/edit_order.inc.php on line 21

Default language and currency problem

**Comment by timint** [comment]
Solved in 1.3.6 softaculous release and 1.3.7.
