### ISSUE TITLE
missing 'fields_customer_password'

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#51]
missing 'fields_customer_password' settings in templates in v2.0

**Comment by litecart** [comment]
fields_customer_password is no longer present in the platform. Did you update to beta2?

**Comment by phrazer** [comment]
hmm confused, if you go to admin - settings - checkout you still got:
 - Password Field (If Register Guests is enabled, show the password field letting customers set their own password. Otherwise randomly generated.)
isn't this (key=fields_customer_password)

why would you cancle this, its a good setting and helps conversion rate, since ppl dont have to write password.

**Comment by litecart** [comment]
We had tons of complains from merchants that customers don't know their passwords. Removing this feature would solve that issue and lighten up some code as well. Setting your password when creating an account is a conventional user experience.

Confirmed issue with settings. Fix coming up. Thanks for reporting.

**Comment by phrazer** [comment]
I really think this is a big mistake. You had one setting you could click and password field is shown. If they are that lazy that they cannot setup one setting (or you could make it default to true) you shouldnt listen them. So much to gain (better conversion rates, more sales) to have this optional setting.

**Comment by timint** [comment]
Nah, trusting a stranger with the keys to your brand new ferrari could be **a big mistake**.

If the discussion would come to lazy customers there are many other aspects that are much more relevant in my opinion than having the customer chosing his password for the account. It's not written in stone. A vqmod could easily turn this around for you.
