### ISSUE TITLE
missing id=logotype in print slip and order copy

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#52]
in template/pages
 - printable_order_copy.inc
 - printable_packing_slip.inc

        <img src="<?php echo document::link(WS_DIR_IMAGES . 'logotype.png'); ?>" alt="<?php echo settings::get('store_name'); ?>" />

should be:
        <img id=logotype src="...

otherwise logo is too big in some situations.

**Comment by litecart** [comment]
Confirmed, thank you.
