### ISSUE TITLE
adding new order from admin error

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#53]
I chose default client ACME and yellow duck (second option) gives this error, when you save it:

		15	ACME Corp. 0000000000	Warning: Passed argument cannot be empty in ~/includes/library/lib_reference.inc.php on line 38
Notice: Trying to get property of non-object in ~/admin/orders.app/orders.inc.php on line 127
-	$18.00 USD	Unprocessed	Apr 4 2017 10:22 AM

**Comment by litecart** [comment]
Confirmed, thank you for reporting.
