### ISSUE TITLE
change language (missing name)

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#54]
This maybe is not a bug, but should be checked not to shown warnings if missing name? But again this situation should not had happen in the first place, since you have to have a name for all languages :)

Which LiteCart version are you running?
![change_lang](https://cloud.githubusercontent.com/assets/138212/24656652/92b5f2fc-1943-11e7-98da-de6a28ffb568.PNG)

**Comment by litecart** [comment]
The errors is a good thing. They will be present in the error log and in your error reports letting you know something definately needs fixing.

Errors are not visible for customers. Only the IP addresses in includes/config.inc.php or logged in administrators.
