### ISSUE TITLE
new language ideas/problems

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#55]
what would be best strategy if we dont live in country that has "en" language. since its baked in system we cannot change its code to another language, and we cannot delete it. The best way as I see is add another language (sl) and leave (en). Not the cleanest solution. A lot of people start with playing with categories and products and then later adds new language and has to do all again.

Dont get me wrong, I like the whole system, database solution for languages and interface to change multiple languages for same product. 

It there possibility that en could be changed (with BIG WARNING when you want to do that) or is it really baked into the system? Or some other solution. Since I think a lot of people use shop in their language and never need 'en' lang.

Another problem/idea is that when you add second language, you should then go MANUALY over every product/category/status/groups/options and write that lang values. Otherwise you get a lot of errors on frontpage. Easy solution would be that that when you add new language, system ask you if you want to copy all values from 'en' language, so you get clean default values. And since a lot of people wrote half of webpage already under en field they only repair what is left.

I hope I didnt complicated this too much :+1: :) 

Lets have a debate about this and find some simple and good solution, if possible.

**Comment by litecart** [comment]
You can disable "en". But en must be present as it's a mandatory component for the translations database. What you can do is extract a CSV, rename the language code, and import back in. That way you copied all the data to the new language fields.

May I recommend the forums for questions and debates. http://www.litecart.net/forums/
