### ISSUE TITLE
Undefined index while trying the 2.0-rc1

### ISSUE THREAD

**Issue by gntech** [litecart/litecart#59]
**What were you trying to do?**
Opening a product in the modal view.
Opening the cart after I have added a product.

**What was expected to happen?**
Nothing special

**What was the actual result - what exactly did happen?**
I got the following error Notice: Undefined index: name in ~/includes/library/lib_cart.inc.php on line 164

I also get the following error when opening the product modal on my test product. Notice: Undefined index: name in ~/pages/product.inc.php on line 142

**Which LiteCart version are you running?**
2.0-rc1

**Comment by timint** [comment]
Have you added a second language? Are the products, quantity units, options translated?

**Comment by gntech** [comment]
Ah thanks! That must be it. :) I have added a second language but I have not updated any translations

**Comment by timint** [comment]
This could indicate a bug in some code for fallback translations. I have my suspicions for quantity unit.

**Comment by timint** [comment]
Any update what causes your issue?

**Comment by gntech** [comment]
I have added some translations but the notice has not disappeared. I will look into this more later today.

**Comment by timint** [comment]
If it's $product->quantity_unit['name'], try editing the quantity unit in Admin -> Catalog -> Quantity Units. Just open and save. It will populate any missing rows in the database.

**Comment by gntech** [comment]
Yes, that did the trick! I opened quantity units and entered some translations and after that the notice disappered.
