### ISSUE TITLE
Pages export

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#61]
<strong>Deprecated:</strong> catalog::page is deprecated. Use instead reference::page in <strong>~/includes/library/lib_catalog.inc.php</strong> on line <strong>6</strong><br />

**Comment by timint** [comment]
Confirmed! Nothing slips by that hawk eye of yours :)

This is a feature recently ported from an 1.x add-on.

Thanks again for reporting. You have shown great value to this project.
