### ISSUE TITLE
Templatesetting: Sidebar Parallax Effect  (False) 

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#62]
Does not work..

**Comment by litecart** [comment]
Unexpectedly `(window.config.template.settings.sidebar_parallax_effect)` resolves to true with the value 0 in it.

In includes/templates/default.catalog/js/app.min.js
Change
`window.config.template.settings.sidebar_parallax_effect)`
to
`window.config.template.settings.sidebar_parallax_effect == true)`

In includes/templates/default.catalog/js/app.js
Change
`if (window.config.template.settings.sidebar_parallax_effect)`
to
`if (window.config.template.settings.sidebar_parallax_effect == true)`

**Comment by gabbo2** [comment]
Even 0 is a value :-)
