### ISSUE TITLE
Updating a catalog: Dock checkbox remains unchecked after opening category for editing

### ISSUE THREAD

**Issue by EduardoG78** [litecart/litecart#7]
No matter what values I save in the dock field (menu,tree), the two checkboxes remain unchecked whenever I edit a category. Sample URL = /admin/?app=catalog&doc=edit_category&category_id=5 .

I've installed the Dutch language, but I don't think that should matter. I've not made any changes to the source code of the admin section at all. I first installed 1.36 and then updated to 1.37 and have successfully run the upgrade-script. 

In phpMyAdmin I can see that the values are indeed saved (values: [blank], menu, dock or "menu,dock"), but whenever I edit the category the checkboxes remain unchecked. So, after saving the category (and not re-checking the checkboxes) the dock field reverts to "" (blank)..

This is the code in catalog.app/edit_category.inc.php:

```
<td><strong><?php echo language::translate('title_dock', 'Dock'); ?></strong><br />
              <label><?php echo functions::form_draw_checkbox('dock[]', 'menu', isset($_POST['dock']) ? $_POST['dock'] : 'menu'); ?> <?php echo language::translate('text_dock_in_menu', 'Dock in top menu'); ?></label><br/>
              <label><?php echo functions::form_draw_checkbox('dock[]', 'tree', isset($_POST['dock']) ? $_POST['dock'] : 'tree'); ?> <?php echo language::translate('text_dock_in_tree', 'Dock in category tree'); ?></label>
            </td>
```

And this is the code in func_form.inc.php:
```
function form_draw_checkbox($name, $value, $input=true, $parameters='') {
    if ($input === true) $input = form_reinsert_value($name, $value);

    return '<input type="checkbox" name="'. htmlspecialchars($name) .'" value="'. htmlspecialchars($value) .'" '. ($input === $value ? ' checked="checked"' : false) . (($parameters) ? ' ' . $parameters : false) .' />';
  }
```

I hope you can check it out.. Something seems to go wrong in form_reinsert_value , because somehow the condition $input === $value doesn't seem to match and 'checked="checked"' is not added to the checkbox. 

Thanks in advance,

Eduardo

**Comment by timint** [comment]
Which LiteCart version are you running?

**Comment by EduardoG78** [comment]
The latest version, 1.3.7.. Originally 1.3.6 was installed and afterwards it was upgraded to 1.3.7 and then the upgrade script was run successfully.

**Comment by timint** [comment]
Confirmed!

In edit_category.inc.php, find

```
              <label><?php echo functions::form_draw_checkbox('dock[]', 'menu', isset($_POST['dock']) ? $_POST['dock'] : 'menu'); ?> <?php echo language::translate('text_dock_in_menu', 'Dock in top menu'); ?></label><br/>
              <label><?php echo functions::form_draw_checkbox('dock[]', 'tree', isset($_POST['dock']) ? $_POST['dock'] : 'tree'); ?> <?php echo language::translate('text_dock_in_tree', 'Dock in category tree'); ?></label>
```

Replace with:

```
              <label><?php echo functions::form_draw_checkbox('dock[]', 'menu', isset($_POST['dock']) ? true : 'menu'); ?> <?php echo language::translate('text_dock_in_menu', 'Dock in top menu'); ?></label><br/>
              <label><?php echo functions::form_draw_checkbox('dock[]', 'tree', isset($_POST['dock']) ? true : 'tree'); ?> <?php echo language::translate('text_dock_in_tree', 'Dock in category tree'); ?></label>
```

**Comment by EduardoG78** [comment]
Thanks a lot for the amazingly quick feedback!

I've updated the edit_category.inc.php with your patch, and it works! Thumbs up!

Cheers, Eduardo

**Comment by timint** [comment]
Thanks for reporting. The fix will be included the next release.
