### ISSUE TITLE
Admin > Settings > Order Copy Recipients - not sending to multiple addresses

### ISSUE THREAD

**Issue by paulgurney** [litecart/litecart#74]
**What were you trying to do?**
We want to add two emails to the `Order Copy Receipients` field.

As it states:  
> Send order copies to the following e-mail addresses. Separate by semi-colons.	

**What was expected to happen?**
We expected to receive emails at each valid address

**What was the actual result - what exactly did happen?**
No email is sent to those emails, after an order is placed.
Note: the usual admin email set in `Store Email` does receive an order alert email.

**Which LiteCart version are you running?**
LiteCart® 1.3.4.1

**Comment by timint** [comment]
Thank you for providing a good fully detailed issue report. 👍

**Comment by timint** [comment]
Can not confirm. The following value worked for the demo store:

development@litecart.net;test@litecart.net

**Comment by paulgurney** [comment]
Ah, I hoped a new version fixed it; how is the upgrade from 1.3.7 to 2.0.1 for an existing store? full data compatibility?

I wonder if the fix was made here:  https://github.com/litecart/litecart/commit/f1549b3a59b0eece1cef328f7a129002503275d2
does that look familiar?

**Comment by timint** [comment]
Nah, the method in ctrl_order only builds the email for a single email address passed. The code that splits multiple addresses is in pages/order_process.inc.php. You can debug that file and also see what is passed to func_email.inc.php.

For upgrades, you can step directly from any old LiteCart version directly to the latest. The upgrade script will handle all previous versions. Don't forget to backup.

**Comment by timint** [comment]
No worries. I'm happy as long as you have a pleasen't experience. I think you will love 2.0.

The coming 2.0.2 will patch an issue with emailing the order copy in a regional language.
