### ISSUE TITLE
Feature Idea: show order# in checkout confirmation screen

### ISSUE THREAD

**Issue by paulgurney** [litecart/litecart#75]
**What were you trying to do?**
When a user completes their cart submission, and receives the **Success** screen, it would be great to (1) show their Order Number and (2) Print that they will get an **email receipt**, to check spam, etc.

**Why?**
It's customary in ecommerce to show the user as much "helpful info" on the confirmation screen to create a sense of confidence and trust. It's an accepted UX design pattern.

Yes, it's true that they do get an **order email**, as well, which is also a great UX design pattern.

** Screen shots **
Like this:
![litecart post order](https://user-images.githubusercontent.com/13963850/26947163-ab97d994-4c5f-11e7-8f95-db36e40c018a.png)

**Which LiteCart version are you running?**
v2.01

**Comment by timint** [comment]
Can be done.

See translation keys **description_order_completed** and **description_click_printable_copy**.

**Comment by timint** [comment]
Added to the current dev branch. Will roll out next release.
