### ISSUE TITLE
admin panel - categories - docking properties not 'remembered'

### ISSUE THREAD

**Issue by rob-lindman** [litecart/litecart#8]
using 1.3.7, downloaded three days ago, I created a category. I specify that I want this to display in the category tree, and click save. 

The category DOES display in the category tree. 

However, when I Edit the category again, it does NOT show that the checkbox is checked.

**Comment by timint** [comment]
Download the hotfix. We already patched this.

**Comment by rob-lindman** [comment]
I downloaded and applied the Hotfix, uploaded it to the server, cleared the PHP7 opcode cache. The behavior has changed, yet is still not fully correct. 

It will save the selection if one or both of the checkboxes is selected. If I don't want a category to appear in either the menu or the tree, yet still want it enabled, it does not save the empty checkboxes. It will revert the checkboxes to the state they were in before I cleared the checkboxes.

Additionally, (feature request), there is a category list at the bottom of the page. It might be useful to have an option to toggle whether or not the category is displayed here. 

The use case for this is I am creating a 'popular' category. I do not want the 'popular' category to appear in any of those three places, it would probably be a 'front page only' feature. I may design a widget to show the items in this category or simply have a link somewhere in the site to go to that category front. There are potentially other use cases for the described 'don't show it anywhere automatically' behavior.

**Comment by timint** [comment]
Confirmed.

In admin/catalog.app/edit_catalog.inc.php

**On line 26, find**

    if (empty(notices::$data['errors'])) {

**After that, add**
      
      if (!isset($_POST['dock'])) $_POST['dock'] = array();

Fix will be included the next version release.

**Comment by rob-lindman** [comment]
this is fixed. thank you ;)
