### ISSUE TITLE
Start page Encoding problem

### ISSUE THREAD

**Issue by mahotilo** [litecart/litecart#81]
LiteCart 2.0.2

1. Open admin console
2. Set Russian Locale (or any Cyrillic)
3. See wrong encoding of Month name in Statistics box

![1](https://user-images.githubusercontent.com/14929385/27873150-b3d4a470-61b3-11e7-8c13-0eadd737819f.png)

**Comment by timint** [comment]
What charset is selected and did you have the right encoding of the file you imported?

**Comment by mahotilo** [comment]
> What charset is selected 
(ISO 639-1)  
ru
(ISO 639-2)  
rus
Encoding
UTF-8
Locale
rus,russian

> and did you have the right encoding of the file you imported?
csv with translation is in UTF-8

Maybe problem in wrong Locale? Month name is setted in admin\stats.inc.php
with strftime('%B'). It should work fine with respect on locale, but..

**Comment by timint** [comment]
Everything seems right but I am unsure about your Locale? Are you on a Windows server? Try ru_RU.utf8 on Linux.

**Comment by mahotilo** [comment]
LC run on local Apache on Windows (USBWebserver 8.6)
LC says that ru_RU.utf8 is not allowed on my server. 

Interesting, that chart axis shows months correctly with `language::strftime('%b', $timestamp).`.

**Comment by litecart** [comment]
Should be resolved by this commit
https://github.com/litecart/litecart/commit/0297e07027a3e44e8b389e802fefaed385d901ad

Rolling out with next master release.
