### ISSUE TITLE
search results

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#83]
ver 2.0

There is lot of problems with searching. If I have product "Žaga" and you search "žaga" or "zaga" both should be shown. Now none is. Or another example: "Cev zalivanje" you search for "Cev" or "cev" and no results. I think search should work for all this examples. I belive problem is with MATCH() AGAINST or BINARY MODE.

Best regards,

**Comment by timint** [comment]
Boolean mode should already be case insensitive:
https://demo.litecart.net/en/search?query=duck

To treat aåäà equally set utf8_general_ci as your mysql collation.
https://stackoverflow.com/questions/7126527/accent-insensitive-searches-problems-with-utf8-general-ci-collation
https://stackoverflow.com/questions/2722044/mysql-german-accents-not-sensitive-search-in-full-text-searches

I'm not sure what the right approach is that suits everyone.

**Comment by phrazer** [comment]
none of this solutions works. I think this is big problem, since lot of stores use non-latin chars and 80% of usage on any shop is search.

**Comment by timint** [comment]
To match partial content

In pages/search.inc.php

Find
`match(pi.name, pi.short_description, pi.description) against ('". database::input($_GET['query']) ."' in boolean mode)`

Change to 
`match(pi.name, pi.short_description, pi.description) against ('*". database::input($_GET['query']) ."*' in boolean mode)`

See the wildcard *

**Comment by phrazer** [comment]
just as reminder, problem with 3char searches, they are not working, even with this patch. 

One more thing I think part of the word "yel" OR "žag" should also work. Problem: https://demo.litecart.net/en/search?query=yel (possible to make this happen?)

possible to solve this? something has to do with MATCH() mysql.

**Comment by timint** [comment]
Have you tried the wildcard *?
See above solution.

The demo does not have this fix yet. If i am correct it will roll out in 2.0.3.
