### ISSUE TITLE
mysql 5.7 problem

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#84]
when you save category or product you get problem with timestamps and default values. Example:

Fatal error: 1364 - Field 'parent_id' doesn't have a default value insert into `tvojshop`.`lc_categories` (date_created) values ('2017-08-23 14:12:33'); in ~/includes/library/lib_database.inc.php on line 220

**Comment by phrazer** [comment]
this fixes problems:

sql_mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

# FIX some old errors
show_compatibility_56 = ON
performance_schema

but I think It would be wise to change SQL file to be compitable with 5.7 version, since its default in most latest Linux versions.

**Comment by timint** [comment]
Have they changed strict mode to enabled if omitted?

I previously have this workaround for the problem with default values:

```
      $sql_mode_query = self::query("select @@SESSION.sql_mode;");
      $sql_mode = self::fetch($sql_mode_query);

      if (strpos($sql_mode['@@SESSION.sql_mode'], 'STRICT_TRANS_TABLES') !== false) {
        $sql_mode['@@SESSION.sql_mode'] = str_replace($sql_mode['@@SESSION.sql_mode'], 'STRICT_TRANS_TABLES', '');
      }

      $sql_mode['@@SESSION.sql_mode'] = trim($sql_mode['@@SESSION.sql_mode']);

      self::query("SET @@session.sql_mode = '". database::input($sql_mode['@@SESSION.sql_mode']) ."';");
```

In the early beginning I did not consider strict sql coding as that was not an issue on until 5.7. I need to rewrite the whole structure to make it comply to strict. But the workaround bought me time.

**Comment by phrazer** [comment]
cool, totaly get you, but looks like default had changed I guess. Because I setup shop on brand new server and errrors started to show. 

Thanks for fast replay and best shop software!

**Comment by timint** [comment]
What does your sql_mode setting look like before changing it?

Thank you for the kind words. :)

**Comment by phrazer** [comment]
https://dev.mysql.com/doc/refman/5.7/en/faqs-sql-modes.html


A.3.7. | What is the default server SQL mode when MySQL 5.7 is installed?
The default SQL mode in MySQL 5.7 includes these modes: ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES,NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, andNO_ENGINE_SUBSTITUTION.

The ONLY_FULL_GROUP_BY and STRICT_TRANS_TABLES modes were added in MySQL 5.7.5. 
TheNO_AUTO_CREATE_USER mode was added in MySQL 5.7.7. The ERROR_FOR_DIVISION_BY_ZERO, NO_ZERO_DATE, and NO_ZERO_IN_DATE modes were added in MySQL 5.7.8. For information about all available modes and default MySQL behavior, see Section 5.1.8, “Server SQL Modes”.

No rpoblem :) :+1:

**Comment by timint** [comment]
Fixed in the dev branch, rolling out next release. See lib_database.inc.php.
