### ISSUE TITLE
email on order problem

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#85]
To be honest, I dont know how I did it, but when customer is writing email and if email is wrong, customer data gets autosaved on order, and then they cannot change email field anymore. But also process order dont work anymore since email is not correct. I attached image if explanation is confusing :)

![capture12122](https://user-images.githubusercontent.com/138212/29994284-45872c26-8fcc-11e7-83b7-05a84589e832.PNG)

**Comment by timint** [comment]
Do you have Register Guests enabled? Which creates an account and logs them in upon inserting their info.

**Comment by phrazer** [comment]
yes

**Comment by timint** [comment]
I think I have this one confirmed. Next should have a fix for this.
