### ISSUE TITLE
A collection of issues in the LiteCart.net site

### ISSUE THREAD

**Issue by kuopassa** [litecart/litecart#87]
The website at www.litecart.net has at the bottom right corner a broken link with anchor text "Bug Tracker". It's pointing to https://bitbucket.org/timint/litecart/issues/. Also link with anchor text "Community Forums" is broken. Thirdly: "Contact" section encourages to inform you about these issues using community forums, but I'm unable to log in there. It seems I've lost my password, and when trying to order a new password by clicking the button with text "Lost Password" it doesn't do anything.

So I would recommend that someone with admin rights would make some coffee and then start clicking links at www.litecart.net to check if there are more issues...

**Comment by timint** [comment]
LOL, you are right. It's time for a dead link scan.
I'll make sure I'll get a size large of that coffee. ;)
