### ISSUE TITLE
Dependencies Update

### ISSUE THREAD

**Issue by Tangol** [litecart/litecart#94]
Please note that for the next version of LiteCart, there are some dependencies that need updating:

- [Trumbowyg](https://github.com/Alex-D/Trumbowyg/releases)

- [featherlight](https://github.com/noelboss/featherlight/releases)

- [chartist-js](https://github.com/gionkunz/chartist-js/releases)

- [vQmod](https://github.com/vqmod/vqmod/releases)

Thanks!

**Comment by timint** [comment]
Are there any new features you wish to get access to from these newer releases?

**Comment by litecart** [comment]
Newer versions added to 2.1
