### ISSUE TITLE
Missing title attribute for icons

### ISSUE THREAD

**Issue by Tangol** [litecart/litecart#95]
Missing `title=" "` attributes for **Packing Slip** and **Order Copy** icons.
![title](https://user-images.githubusercontent.com/3336728/33347781-ba52e364-d49c-11e7-9eb9-13022418adcf.png)

Also, found another one at **Stock Options**.
![stock](https://user-images.githubusercontent.com/3336728/33348130-c882ee88-d49d-11e7-96b5-6060dfceec2a.png)

Which LiteCart version are you running?
**2.0.2**

**Comment by timint** [comment]
All feedback is valuable. Thank you.
