### ISSUE TITLE
problem with text over lappping

### ISSUE THREAD

**Issue by garrytodd** [litecart/litecart#97]
Hi text overlaps on campaigns please see image discount and price merged

please tel me how to fix
![collins music](https://user-images.githubusercontent.com/6689552/33377808-aa75909a-d50a-11e7-8d7d-1645d2fc79d9.jpg)

**Comment by litecart** [comment]
Not a bug. If the title has variable height you would get variable height of the boxes as well. What you can do is remove the css styling that prevents word wrapping and set a fixed height.
