### ISSUE TITLE
Link from slideshow not active (z-index error?)

### ISSUE THREAD

**Issue by Bazylich** [litecart/litecart#99]
Slideshow picture link is linking when enable is only one picture and without Caption.

If I'am adding Caption or enable second picture to slideshow linki is "coverd" and not active - cursor is default not pointer, and clicking don't do anything .

I tested this in demo store - behavior is that same.
LiteCart 2.0.2

**Comment by timint** [comment]
Thank you for reporting.

This is a limitation in ResponsiveSlides. It was recently reported and solved in 2.1-dev by replacing it with Bootstrap Carousel.

**Comment by Bazylich** [comment]
Thank you Tim - I added to 2.02 only files with Bootstrap Carousel elements (js, less, box) from version 2.1-dev and it is ok.
